src/kex/test_kex.c
src/kex_rlwe_bcns15/fft.c
src/kex_rlwe_bcns15/kex_rlwe_bcns15.c
src/kex_rlwe_bcns15/local.h
src/kex_rlwe_bcns15/rlwe.c
src/rand/rand.c
src/rand/test_rand.c

Memory leak was caused by a possible partial allocation of the arrays in
`oqs_kex_rlwe_bcns15_fft_ctx`.
Allocate fixed size arrays in the `oqs_kex_rlwe_bcns15_fft_ctx` struct
rather then calling an initialization function afterwords. Also specify
fixed array sizes in functions where possible.

Fixes memory leak and moves allocation into stuct.

---

src/kex/kex.c
src/kex/kex.h
src/kex/test_kex.c
src/kex_rlwe_bcns15/kex_rlwe_bcns15.c
src/kex_rlwe_bcns15/kex_rlwe_bcns15.h

This will allow key exchange modules to support a variety of security levels using the same interface, specified via an optional named_parameters argument.

Add named parameters to OQS_KEX constructor.

---

src/rand_urandom_chacha20/rand_urandom_chacha20.c

I added the CRYPT_VERIFYCONTEXT flag to tell CAPI we won't need access to a key container in the following uses of the requested context. This fixes an error on machines without an initialized key container for the current user.

Fixed Windows Crypto API rand call on uninitialized machines.

---

README.md
VisualStudio/oqs/oqs.vcxproj
VisualStudio/test_kex/test_kex.vcxproj
VisualStudio/test_rand/test_rand.vcxproj
src/kex_rlwe_bcns15/kex_rlwe_bcns15.c
src/rand_urandom_chacha20/rand_urandom_chacha20.c

Changed two things:
* Reverted back to using strdup (instead of _strdup), because that didn't link well with OpenSSL. I disabled the SDL checks to downgrade the deprecate error a warning.
* I now link with the system runtime statically, to be compatible with OpenSSL's Windows build system.
These changes allow me to integrate OQS in OpenSSL.

Modified OQS Windows projects to make it compatible with OpenSSL on Windows

---

.travis-style-check.sh
.travis.yml
src/kex/kex.h
src/rand/rand.h

I added a check on travis to verify that 
```
make prettyprint
```
was run before pushing in the PRs. The tests successfully catched the fact that `make prettyprint` in `master` [should have been run](https://travis-ci.org/tlepoint/liboqs/builds/168086027), and the second commit makes the [checks all green](https://travis-ci.org/tlepoint/liboqs/builds/168086535).
Note that I could not use the astyle package in Ubuntu 12.04 (that is used in Travis): it is an old version of astyle which (1) does not have the same output behavior, and (2) does not behave the same.

Adding prettyprint check to Travis

---

src/kex/kex.h

Several parameters should be more general. This is already reflected by the byte-pointer type, but the documentation should also reflect this.

Comment updates

---

src/aes/test_aes.c
src/ds_benchmark.h
src/kex/test_kex.c
src/kex_lwe_frodo/kex_lwe_frodo.c
src/kex_rlwe_newhope/kex_rlwe_newhope.c

Cleaned up a couple memory leaks.
The first is pretty straight forward; the named_parameters weren't being freed properly.
The second fix is for the running the speed tests; TIME_OPERATION_SECONDS was being used to time running some functions, but when those functions allocated memory, it was never cleaned up.
To fix this, I added a TIME_OPERATION_SECONDS_CLEANUP method. It is just the same as TIME_OPERATION_SECONDS, but takes an optional `cleanop` parameter that runs after each iteration.
Verified using valgrind:
valgrind --leak-check=full ./test_kex
valgrind --leak-check=full ./test_aes
valgrind --leak-check=full ./test_rand

Fix memory leak

---

src/kex/test_kex.c

Was getting annoyed with having to run all the tests when working on a single algorithm.
`./test_kex -ls` will list the algorithms available and then you can run for example `./test_kex frodo` to run only the frodo tests and benchmark.

Add option to only run tests/benchmarks for a single algorithm.

---

.travis-banned-functions-check.sh
.travis-global-namespace-check.sh
.travis-style-check.sh
.travis.yml

Make style check fail when astyle fails.

Revert the previous change in 250681196f

---

Makefile
docs/Algorithm data sheets/kex_rlwe_bcns15.md
src/kex_rlwe_bcns15/kex_rlwe_bcns15.c

Clang scan-build does not like it when `malloc` uses `sizeof` for its input and the type does not match the variable it is assigned to. For example `uint8_t = malloc(10*sizeof(uint64_t)`.  This is because writing the wrong type is a common source of errors. 
I changed the code to reflect this and we can now run `scan-build` over our entire build with no errors or warnings reported.
I also made `make clean` not delete the algorithms data sheet folder.

Fixes for scan-build and make.

---

Makefile
README.md
src/crypto/aes/test_aes.c
src/crypto/rand/test_rand.c
src/kex/test_kex.c

The quiet option does disables the printing of keys in the output.
Benchmarking is now turned off by default unless the bench option is passed to test_kex.

Add quiet and bench options for test_kex.

---

Makefile

- Solves #81: the directory `objs/kex_sidh_cln16` was not created.
- Removes the "\t"'s: problems when using `echo`, `echo -e`, `/bin/echo -e`, etc. on different architectures.

Solves #81: dir was not created

---

README.md
acinclude.m4

patch contains some spelling fixes ( just in comments ) as found by a bot ( https://github.com/ka7/misspell_fixer ). Any upcoming License changes (e.g. GPL2 to GPL3+) are hereby granted.

spelling fixes

---

README.md

I've built the library on Ubuntu 16.04 and here are the commands to install the dependencies.
I've also found a small mistake in the Readme: to build with kex_code_mcbits enabled the command is not `./configure --enable-libsodium` but `./configure --enable-mcbits`.

Update Readme with Ubuntu commands

---

README.md

Nothing special, just a typo.
Peace

Typo: s/director/directory

---

src/kex_mlwe_kyber/indcpa.c
src/kex_mlwe_kyber/ntt.c
src/kex_mlwe_kyber/poly.c
src/kex_mlwe_kyber/polyvec.c
src/kex_mlwe_kyber/reduce.c
src/kex_mlwe_kyber/verify.c

Fixing #137. The output of 
```
nm -g liboqs.a | grep ' T ' | grep -E -v -i ' T [_]?[OQS|ntru_]'
```
was empty.

Removing non-namespaced global symbols from Kyber

---

src/kex_rlwe_msrln16/AMD64/error_asm.S
src/kex_rlwe_msrln16/AMD64/ntt_x64_asm.S
src/kex_sidh_cln16/AMD64/fp_x64_asm.S

replaced .global with .globl in all .S files due to ancient “as” tool
in macOS

Fix unknown pseudo-op: .global under macOS

---

docs/Algorithm data sheets/kex_sidh_cln16.md
docs/Algorithm data sheets/sig_picnic.md

Added datasheets for SIDH and Picnic.

---

README.md
bench-memory.sh
kex_bench_memory.sh
src/kex/test_kex.c

Add options which enable memory usage profiling of KEX algorithms.
Changelog:
- added `--mem-bench` option which quitly runs a test case just one
- added `--seconds` option to specify for how long an option should be run during benchmarking
- added `kex_memory_bench.sh` script which uses Valgrind's Massif tool to present a memory usage graph
Sponsored by [Sectra Communications](http://communications.sectra.com/)

KEX memory benchmarks

---

src/kex_code_mcbits/kex_code_mcbits.c
src/kex_lwe_frodo/kex_lwe_frodo_macrify.c
src/kex_mlwe_kyber/kex_mlwe_kyber.c
src/kex_ntru/kex_ntru.c
src/kex_rlwe_bcns15/kex_rlwe_bcns15.c
src/kex_rlwe_msrln16/kex_rlwe_msrln16.c
src/kex_rlwe_newhope/kex_rlwe_newhope.c
src/kex_sidh_cln16/kex_sidh_cln16.c

This changeset mainly adds code to consistently initialize out-parameters to NULL. This is important so we don't call free() on any invalid pointers in the failure path.
I also added code that clears out-parameters on failure, where such code was not already in place. It's generally considered good manners to not leak invalid pointers, even when returning an error code.
SIDH IQC REF has not been reviewed for this changeset since it doesn't consider failures at all, and would need a larger restructuring to get up to par.

Initialize out-parameters to NULL

---

src/kex_code_mcbits/kex_code_mcbits.c

This change adds the bare minimum checks to ensure input data is valid. In the specific case of McBits providing too little data will result in a memcpy operation reading beyond the buffer. A similar read will typically return garbage data but could also induce a crash if it crosses into a guard page or uncommitted page.

Add checks to verify length of input data for McBits

---

.travis-tests.sh
Makefile.am
configure.ac
src/kex_lwe_frodo/lwe_noise.c
src/kex_ntru/ntru_crypto_ntru_encrypt.c
src/kex_sidh_cln16/SIDH_setup.c
src/kex_sidh_cln16/ec_isogeny.c
src/kex_sidh_cln16/kex_sidh_cln16.c

FALSE POSITIVE
-------------
CID 1411664 (#1-8 of 8): Untrusted pointer read (TAINTED_SCALAR)
src/kex_rlwe_bcns15/fft.c
Comments:
False positive if SHA_INIT flag set.  It's always set.
CID 1458082:    (UNINIT)
/src/kex_ntru/ntru_crypto_sha256.c: 105 in ntru_crypto_sha256_digest()
/src/kex_ntru/ntru_crypto_sha256.c: 105 in ntru_crypto_sha256_digest()
Comments:
False positive if SHA_INIT flag set. It's always set.
CID 1458079:    (UNINIT)
/src/kex_ntru/ntru_crypto_sha1.c: 676 in ntru_crypto_sha1_digest()
/src/kex_ntru/ntru_crypto_sha1.c: 676 in ntru_crypto_sha1_digest()
CID 1411663 (#1 of 1): Resource leak (RESOURCE_LEAK)
/src/crypto/rand/rand.c
CID 1458078 (#1 of 1): Out-of-bounds access (ARRAY_VS_SINGLETON)
src/kex_sidh_cln16/ec_isogeny.c in oqs_sidh_cln16_phn15()
CID 1458075 (#1 of 1): …

Covscan defect fix

---

.travis/style-check.sh

Separate .gitignore check prior to prettyprint check.

Separate .gitignore check prior to prettyprint check

---

VisualStudio/oqs/oqs.vcxproj
src/common/oqs.h
src/kex/kex.h
src/sig/sig.h

Moved winconfig to oqs include dir in VS pre-build steps, so it can be used by downstream projects (e.g., OpenSSL). Changed references to <oqs/winconfig.h>.

Moved winconfig to oqs include dir

---

VisualStudio/oqs/oqs.vcxproj

Added post-build step to merge the oqs and picnic library in x64 static VS projects, to simplify downstream integration (mirroring the Linux build). This is needed for cleaner OpenSSL integration.
Also removed forced rebuild params of picnic in oqs.

Added post-build step to merge the oqs and picnic library on Windows

---

src/sig/sig.c
src/sig/sig.h
src/sig_picnic/sig_picnic.c
src/sig_picnic/sig_picnic.h

Fixes private key length (issue #227) and adds free functions to sig api to clean up internal ctx memory.

Fixes mem leak issue in sig_picnic

---

README.md
configure.ac
src/sig_picnic/Makefile.am

Fix build on ARM (that has been failing since Picnic was merged directly into OQS).
- added logic to configure.ac to detect presence on ARM
- added logic to picnic's Makefile.am to properly set flags
- removed arm-specific restriction from the readme
Welcoming suggestions on better configure/makefile logic.

Fix build on ARM

---

src/kex/kex.h

Older versions of gcc (4.5.2 in particular) don't understand a
forward typedef and complain a type is redefined when it sees the
actual definition.
Change OQS_KEX to refer to itself as "struct OQS_KEX" in its definition
to remove the need for this forward definition and avoid the redefinition
error on older versions of gcc.

Don't use forward typedefs to avoid break on older GCC

---

.travis/algorithm-datasheets-check.sh
docs/algorithms/kem_frodokem.md
docs/algorithms/kem_kyber.md
docs/algorithms/kem_newhopenist.md
src/kem/crystals-kyber/kem_kyber.c
src/kem/frodokem/kem_frodokem.c
src/kem/kem.c
src/kem/kem.h
src/kem/newhopenist/kem_newhopenist.c
src/kem/speed_kem.c
src/kem/test_kem.c

I was using an enum for algorithm identifiers, and some code assumed that these were sequential.  Assuming sequential means that if we want to remove an algorithm, we can't have gaps. So we'd have to reassign numbers.  But then this would mean binary incompatibility between different versions of liboqs nist-branch.  We also could not have binary compatibility with liboqs master (once master gets the new KEM API) because a different order of KEMs.  So I am trying strings for algorithm identifiers.

Try changing algorithm identifiers to strings

---

Makefile
src/sig/example_sig.c
src/sig/kat_sig.c
src/sig/speed_sig.c
src/sig/test_sig.c

Identified by @tlepoint in #319 but doing as a separate pull request so it gets into the July snapshot release of nist-branch.

Fix opened message length to match NIST/SUPERCOP/Nacl conventions

---

src/kem/crystals-kyber/Makefile
src/kem/newhopenist/Makefile
src/sig/qtesla/Makefile

I have added -march=native compiler flag to Makefiles in qTesla, NewHope, and Kyber subdirectories. It has noticable effect on qTesla and NewHope, but it seems that Kyber has similar results with or without the flag.

-march=native compiler optimization added for qTesla, NewHope and Kyber

---

Makefile.am
README.md
tests/Makefile.am

A previous change broke `make install`.  I looked into how to handle test programs, and rather than using our own `noinst_binPROGRAMS`, apparently automake has a built-in type `check_PROGRAMS`, so I switched to using that.

Switch automake to using check for test programs that aren't installed

---

Makefile.am

Don't symbolically link liboqs.a in make links

---

src/sig/sig.c
src/sig/sig.h
src/sig_picnic/external/picnic.c
src/sig_picnic/external/picnic.h
src/sig_picnic/sig_picnic.c
src/sig_qtesla/external/qTESLA_I.c
src/sig_qtesla/external/qTESLA_I.h
src/sig_qtesla/external/qTESLA_III_size.c
src/sig_qtesla/external/qTESLA_III_size.h
src/sig_qtesla/external/qTESLA_III_speed.c
src/sig_qtesla/external/qTESLA_III_speed.h
src/sig_qtesla/external/qTESLA_api.c
src/sig_qtesla/sig_qtesla.c
src/sig_qtesla/sig_qtesla.h
tests/minimal_sig_oqs.c
tests/test_sig.c

Removed OQS_RAND object; harmonized params names with nist-branch. The sign/verify functions however remain. Fixes issue #374. Supersedes PR #375.

Refactored sig API

---

README.md

Should not `make` before configuring the build.

Too early to make

---

.gitignore
.travis.yml
.travis/all-tests.sh
docs/.Doxyfile

Removing remnants of KEX sidh_msr. The tests pass on Linux, so I'm assuming this work is OK.
Previous work merged into master looks to have cleaned up sidh_msr references in the makefiles etc.
EDIT: windows/Vis Studio specific content still needs to be removed.

Remove residual KEX sidh_msr (#369).

---

src/kem/BIG_QUAKE/kem_BIGQUAKE.h
src/kem/bike/kem_bike.h
src/kem/crystals-kyber/kem_kyber.h
src/kem/frodokem/kem_frodokem.h
src/kem/ledakem/kem_ledakem.h
src/kem/lima/kem_lima.h
src/kem/newhopenist/kem_newhopenist.h
src/kem/saber/kem_saber.h

Cleanup for issue: https://github.com/open-quantum-safe/liboqs/issues/357
I've left extern in the sigs for another issue/PR.

Remove superfluous extern keywords from KEMs.

---

Makefile
docs/algorithms/kem_BIG_QUAKE.md
docs/algorithms/kem_frodokem.md
docs/algorithms/kem_kyber.md
docs/algorithms/kem_ledakem.md
docs/algorithms/kem_lima.md
docs/algorithms/sig_picnic.md
docs/algorithms/sig_qtesla.md
src/kem/BIG_QUAKE/kem_BIGQUAKE.c
src/kem/bike/kem_bike.c
src/kem/crystals-kyber/kem_kyber.c
src/kem/frodokem/kem_frodokem.c
src/kem/kem.h
src/kem/ledakem/kem_ledakem.c
src/kem/lima/kem_lima.c
src/kem/newhopenist/kem_newhopenist.c
src/kem/saber/kem_saber.c
src/kem/sike/kem_sike.c
src/kem/titanium/kem_titanium.c
src/sig/crystals-dilithium/sig_dilithium.c
src/sig/picnic/sig_picnic.c
src/sig/qtesla/sig_qtesla.c
src/sig/sig.h

Added version string attribute for KEMs and SIGs.
Added unique version details for most KEM algorithms, where the upstream code could be explicitly matched to a version on GitHub, the NIST PQ site, or the algorithm web page.
Stubbed out the SIG versions, but could not specify versions. The SIG code in liboqs was different to the repos or files provided online.

Add algorithm version strings and details to NIST branch 

---

Makefile

`/bin/sh` doesn't necessarily understand `[[`. 
```
root@18a2f0f4f26e:/# /bin/sh
/bin/sh: 1: [[: not found
```

Don't rely on bashism in Makefile

---

README.md
config/detect_host_and_cpu.m4
src/sig/picnic/external/endian_compat.h

See title. I added some additional instructions in the Readme that explain the OpenBSD specific steps in the build process.
The changes to picnic were necessary to prevent a double definition error.
One thing that would be nice to have, that i haven't figured out how to do right (since I'm not too familiar with automake) would be setting the default compiler to clang for OpenBSD.
OpenBSD's gcc is based on an old version that does not support several of the newer compilation flags used in the build process and thus can not build this project.

Add support for building on OpenBSD

---

VisualStudio/oqs/oqs.vcxproj

Modified OQS project to preserve the source folder hierarchy in output directory to avoid object file collisions.

Unflatten object file output directory.

---

Makefile.am
tests/Makefile.am

This adds the correct linker instructions when OpenSSL is enabled. It also removes the now-redundant linker instructions when building the tests.
Fixes #485.

Link main liboqs library to OpenSSL when enabled

---

Makefile.am
src/crypto/aes/aes.c
src/crypto/aes/aes_ni.c
tests/Makefile.am
tests/test_aes.c

While working on something else, I noticed that the options from configure to select the different AES configurations weren't actually getting used, so it was always using the plain C AES implementation even when we directed it to use the AES_NI or OpenSSL AES implementations.  This patch fixes that.

Fix macros so AES version compilation actually works

---

src/common/pqclean_shims/aes.h
src/crypto/aes/aes.c
src/kem/frodokem/pqclean_frodokem1344aes_clean/matrix_aes.c
src/kem/frodokem/pqclean_frodokem640aes_clean/matrix_aes.c
src/kem/frodokem/pqclean_frodokem976aes_clean/matrix_aes.c

liboqs has several AES implementations available to it, one of which (OpenSSL EVP) requires that the key schedule be allocated on the heap and release after use.  In particular it cannot be done on the stack (https://github.com/openssl/openssl/issues/962#issuecomment-208792020).  This patch adds a release function for the AES key schedule in the PQClean shims.
Depends on #496.

Update PQClean implementations to have AES key schedule release

---

src/sig/picnic/sig_picnic.c
tests/test_sig.c

The picnic2 code checks that the sig_len value is large enough before serializing the signature, but OQS treats this value as an output variable, so I explicitly set it before calling the low-level picnic2 API.
I also removed now superfluous code from the unit test to achieve the same thing (that was added when picnic2 was integrated).
This should unblock [OpenSSL's PR102](https://github.com/open-quantum-safe/openssl/pull/102), adding picnic2 as an auth method.

Explicitly set the picnic sig_len value before calling the picnic API

---

appveyor.yml
src/kem/sike/config.h

This fixes a build failure on Visual Studio x86 (SIKE wasn't recognizing this as a valid platform). Also adds x86 as an appveyor test platform.

Fix build failure on Visual Studio x86

---

.gitignore

Added .cache (created by python test framework) to .gitignore. The cache is deleted after a successful run of the tests, but not if there is an error; its presence later prevents the test_style.py test to pass and therefore blocks commits.

Added .cache to .gitignore.

---

src/kem/bike/Makefile.am

Compilation of the new BIKE code failed on my Mac.  The problem seems to be that the assembly code uses directives that aren't present in Mach-O binaries.  Examples of the error messages below.  Initial fix is just to switch to having BIKE use only C code on macOS.  This was missed by the Travis continuous integration tests because those host machines don't support AVX2 instructions, so the C code as being used anyway on them.
```
additional/converts.S:83:1: error: unknown directive
.hidden OQS_KEM_bike1_l1_cpa_convert_to_redundant_rep
^
additional/converts.S:84:1: error: unknown directive
.type OQS_KEM_bike1_l1_cpa_convert_to_redundant_rep,@function
^
additional/converts.S:177:1: error: unknown directive
.size OQS_KEM_bike1_l1_cpa_convert_to_redundant_rep,.-OQS_KEM_bike1_l1_cpa_convert_to …
```

Use C code for BIKE on macOS

---

src/sig/qtesla/Makefile.am

Got a bunch of build failures overnight in liboqs and relying applications, related to the function `OQS_SHA3_cshake128_simple4x` not being defined.  After diagnosing, I think it's because the sha3.h file wraps `OQS_SHA3_cshake128_simple4x` in `#if defined ` demanding AVX2 and AES instructions, but the qTesla Makefile only checks for AVX2 instructions before enabling the optimized version.  And unfortunately some of our CircleCI test platforms seem to have AVX2 but not AES.  So I propose just updating the qTesla Makefile to check for AVX2 and AES.  The alternative would be to change sha3.h to only demand AVX2, but I didn't know if the source code for that implementation actually depends on AES instructions or not.

OQS_SHA3_cshake128_simple4x only defined if both AES and AVX2 instructions available

---

tests/helpers.py
tests/test_kat.py

Changed test_kat.py test to also check for AES instructions when branching for qtesla AVX2 KAT file; both are required for avx2 optimization. The travis VM using gcc5 had support for avx2 but not aes, therefore defaulting to the non-optimized code but comparing with avx2 KATs.
Fixes issue #572.

Fix nightly qtesla failure on gcc5

---

tests/example_sig.c

Ported latest example_kex changes to example_sig. In particular, example_sig now returns failure correctly.

Harmonized example_sig with example_kem.

---

src/sig/qtesla/Makefile.am
src/sig/qtesla/avx2/config.h
src/sig/qtesla/portable/config.h
tests/test_kat.py

qtesla's avx2 assembly only targets linux, so this PR disables the optimization on darwin.
Addresses issue #571.

Disabled qtesla avx2 optimizations on darwin

---

.circleci/config.yml

Added testing as per [this discussion](https://github.com/baentsch/testing/wiki/Docker-image-goals) for Centos7 & 8. Arguably testing should only be nightly (iff some code changed) --> Moving new targets `centos-7` and `centos-8` down to the nightly section suggested (as would be testing target configs only either at check-in/`build` _or_ `nightly`).

Centos testing added

---

config/ax_check_x86_features.m4
config/features.m4
src/kem/bike/Makefile.am
src/kem/bike/additional/secure_decode_avx2.c

This PR addresses issue: https://github.com/open-quantum-safe/liboqs/issues/590
GCC-5 supports AVX512-F but not AVX512-BW that is required by BIKE. Added a new macro USE_AVX512_INSTRUCTIONS that is true only when the compiler supports AVX512-F/BW/DQ.

Compiling BIKE without AVX512-BW fix

---

src/kem/bike/additional/secure_decode_avx512.c

Fix for: https://circleci.com/gh/open-quantum-safe/liboqs/3420
On GCC-6 The AVX512 intrinsic `out = _mm512_slli_epi64(a, count)` is translated to the assembly instruction `vpsllq` that expects the immediate value (count) to be a constant. In contrast, the AVX512 intrinsic `out = _mm512_sllv_epi64(a, count)` is translated to the assembly instruction `vpsllvq` that expects count to be a 512-bit variable.
When count is not a constant (as in BIKE) GCC-6 outputs an error message 
> error: the last argument must be an 8-bit immediate
while GCC-7 and above automatically translate `_mm512_slli_epi64` to `_mm512_sllv_epi64`.
In this PR I manually replaced `_mm512_slli_epi64` with `_mm512_sllv_epi64` to fix the compilation on GCC-6.

Fixing BIKE compilation with GCC-6

---

.circleci/config.yml
.travis.yml
README.md
config/external-libraries.m4
src/crypto/sha2/sha2_ossl.c
src/crypto/sha3/sha3_ossl.c

Fixes #565.
Does so by requiring OpenSSL version 1.1.0 or higher.  But one of our target platforms (Ubuntu Xenial 16.04) only comes with OpenSSL 1.0.2.  So what should we do?  Require users on that platform to build OpenSSL 1.0.2 (and update our Docker images accordingly)?  Or remove that as a target platform?  Thoughts, @baentsch and @xvzcf?

Use OpenSSL's EVP_MD_CTX_new and _free

---

tests/helpers.py

I'm sorry, this patch was supposed to be included in my last pull request https://github.com/open-quantum-safe/liboqs/pull/610. Without it, tests do not pass when cross-compiling on Linux. Mingw-w64 builds executables with the ".EXE" extension, which is not expected by the script that runs the tests.

Reworked search for executable files in tests

---

CMakeLists.txt

CMAKE_CL_64 is discouraged and causes errors when building through Mingw-w64 on Windows

Fixed detection processor architecture

---

CMakeLists.txt

The proposed build type "Generic" generates a variant that can run on Intel CPUs regardless of feature set _and_ is O3 compiled. For the time being, arguably the best docker-build target for execution on all x86_64s (incl. CPU-heterogeneous CI environments): When doing TLS-handshake perf tests (openssl s_time), often, AVX2-enabled code executed _slower_ than non-optimised code... Did you encounter this too? Possibly relevant reference: https://blog.cloudflare.com/on-the-dangers-of-intels-frequency-scaling/

generic optimized build type added

---

.CMake/sanitizers.cmake

This should help track where it's crashing.
Not entirely sure on how CMake manages flags, might be a better way to handle this.

Add -g3 debug information to ASAN builds

---

src/sig/picnic/CMakeLists.txt

AVX2 code only works on Linux; change cmakelist.txt file accordingly. Addresses issue #653.

Only enable picnic avx2 on Linux

---

src/sig/picnic/external/endian_compat.h

Fix typo in picnic algorithm.
AATR_CONST should be ATTR_CONST.

Fix typo in picnic.

---

.CMake/toolchain_rasppi.cmake
.CMake/toolchain_windows-amd64.cmake

Correct typo of filename in Raspberry Pi toolchain file so the command can be directly copied and pasted to use.
Add a comment to the Windows toolchain to indicate the necessary package to install to get the necessary cross-compilers, as is already done for the Raspberry Pi toolchain file.

Comment-only fixes to cross-compiling toolchain files

---

.circleci/config.yml
scripts/copy_from_pqclean/tests/kat_sig.c/combine_message_signature.fragment
src/sig/picnic/external/picnic2_simulate.c.i
tests/kat_sig.c

@christianpaquin Fixes a memory leak in Picnic2 that should be propagated upstream.
Fixes #604.

Fix AddressSanitizer issues and enable in nightly runs

---

src/sig/picnic/external/oqs_picnic_macros.h

Don't redefine NDEBUG in Picnic code; fixes warning when building cmake release build.

Avoid picnic macro redefinition

---

.circleci/config.yml
README.md

As workaround enable CCI-Win testing only on mb-* tagged branches (Thanks @dstebila for the suggestion) + added IBM Research attribution

limit Win-testing to mb-* branches; add ibmr attribution

---

.gitattributes

This should force the handling of trailing whitespace and newlines a bit better.
There is more that you can do, such as not allowing tabs in indentation etc, but that possibly breaks some peoples branches (I see a bunch of files having tabs at the start of lines in this repository).

Add a basic .gitattributes file

---

src/kem/kem.h

Building the library ends with an error when `OQS_ENABLE_KEM_SIKE` is disabled.
```
[archie@archlinux build]$ cmake -GNinja -DOQS_ENABLE_KEM_SIKE=OFF ..
-- The C compiler identification is GNU 9.3.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Found OpenSSL: …
```

SIDH build fix

---

.CMake/alg_support.cmake

Without this, cmake-time `-D` settings for default algs have no effect

default alg setting brought in line with documentation

---

tests/kat_kem.c
tests/kat_sig.c

`kem_kat` and `sig_kat` never end with an error because the `ret` variable is overwritten with `OQS_SUCCESS`

Fixing test behavior

---

README.md

OQS_USE_CPU_EXTENSIONS has to be OFF in the cross-compiling scenario, or CMake will fail.

Update cross-compiling instructions for Windows in README.md

---

tests/ds_benchmark.h

Resolves issue #776 when attempting to build for arm64-v8a in clang.
Would also like advice on whether `_bench_init_perfcounters` parameters and local variables should be unsigned, as it would make sense to fix them here.

Change return value of `USING_TIME_RATHER_THAN_CYCLES` to unsigned int.

---

.circleci/config.yml

As once discussed with @xvzcf and to draw on the "catch" by the Centos8 CI test on PR #780 this is to add more CI platforms.
The tests are running (results [here](https://app.circleci.com/pipelines/github/baentsch/liboqs/291/workflows/11fba35f-c766-453c-9a56-6875ede52af2)) so this PR seems OK. 
The results warrant investigation, though:
Quickly looking into the newly emerged failures show 
- a wrong file-extension check for OSX [here](https://github.com/open-quantum-safe/liboqs/blob/7f7bbaf59e9bc1847c7ffc9efe298409a0b71ea2/tests/test_namespace.py#L15) and 
- failures when testing several (15) algorithms (e.g., BIKE1-L3-FO, SIKE-p751-compressed, FrodoKEM-976-AES). When running them manually, it's always a SIGSEGV (core dump): Quick gdb runs show the error in functions like …

adding alpine, shared OSX CI

---

src/kem/bike/CMakeLists.txt
src/sig/picnic/CMakeLists.txt

This is to replace #780 with a 'clean' rebased version easier to review.
CCI ran [here](https://app.circleci.com/pipelines/github/baentsch/liboqs/300/workflows/b063de77-5b43-4214-be08-e799481f3632)

streamlined fix for #779

---

.circleci/config.yml
tests/test_namespace.py

Correct namespace test for shared libs on OSX; moved (still failing) alpine tests to nightly.
CCI [ran here](https://app.circleci.com/pipelines/github/baentsch/liboqs/301/workflows/f346db45-3413-4bf1-a132-9e4ca6e19f87)

fixed shlib OSX namespace test; moved alpine to nightly

---

src/CMakeLists.txt

Now installs `liboqs.dll` in the output bin directory when cross-compiling the shared libs for Windows. Fixes issue #773.

Install dll in output bin directory on windows cross-compile

---

src/sig/dilithium/pqclean_dilithium2_avx2/rounding.c
src/sig/dilithium/pqclean_dilithium3_avx2/rounding.c
src/sig/dilithium/pqclean_dilithium4_avx2/rounding.c

Temporary workaround for #793 until proper fix developed in https://github.com/pq-crystals/dilithium/issues/31
* [No] Does this PR change the the list of algorithms available -- either adding or removing?  (If so, PRs in OQS-OpenSSL, OQS-BoringSSL, and OQS-OpenSSH will also be required by the time this is merged.)

Use C rounding code in Dilithium instead of AVX2

---

.circleci/config.yml
src/common/aes/aes.c
src/common/aes/aes.h
src/common/aes/aes128_ni.c
src/common/aes/aes256_ni.c
src/common/aes/aes_local.h
src/kem/bike/additional/aes_wrap.h

Fixes a few bugs related to the introduction of AES-NI code.  In particular:
- Makes sure the key schedule is actually being set for decryption.
- Uses the type `__m128i` rather than `__m128i_u` since some compilers choke on the latter.
- Notes in the API documentation that output arrays for AES must now be aligned to a 16-byte boundary, and applies this to BIKE.
- This was the cause of the BIKE crash in #799.
- Most AES calls in BIKE seemed to have been aligned, but the `sk_t` `sigma0->raw` and `sigma1->raw` members were not, which was causing the crash.  
- The solution I took for BIKE was to wrap the AES call in a wrapper that ensures it's always aligned [[aes_wrap.h, line 41]](https://github.com/open-quantum-safe/liboqs/pull/800/files#diff-c3f72798cb0514e552cfcdd92d68a116R41). I tried …

AES-NI bug fixes

---

src/common/aes/aes.c

Fixes #814.
* [No] Does this PR change the the list of algorithms available -- either adding or removing?  (If so, PRs in OQS-OpenSSL, OQS-BoringSSL, and OQS-OpenSSH will also be required by the time this is merged.)

Some missing ifdef's around CPU extension code

---

src/sig/picnic/external/compat.h

Appveyor installed a newer version of MSVC (from 19.26.28806.0 to 19.27.29111.0), which resulted in failures on the nightly build. This PR tweaks the picnic include files to accommodate this change.

Fix appveyor test failures

---

.circleci/config.yml

Resolves CI build failures for macOS shared as described in #821 that were hanging on a Doxygen test.  Unclear why they were hanging.  However Doxygen is being tested on other platforms in the CI matrix, so the simplest solution at this point is just to skip that test on this particular build configuration.
Fixes #821.
* [No] Does this PR change the the list of algorithms available -- either adding or removing?  (If so, PRs in OQS-OpenSSL, OQS-BoringSSL, and OQS-OpenSSH will also be required by the time this is merged.)

Skip Doxygen test that's hanging on CircleCI macOS Shared

---

src/common/common.c
tests/system_info.c

This ensures that only the combination of build- _and_ runtime-CPU-featuresets are reported, not just runtime feature sets. The latter led to wrong result interpretation in performance testing.

correct compile time feature display

---

scripts/copy_from_pqclean/copy_from_pqclean.py

Allows excluding specific algorithm families from "copy_from_pyclean" by setting the environment variable "NOT_READY" to those names, e.g., `export NOT_READY=hqc`) when running that script.
This would allow piecemeal progress until all upstream errors are resolved (e.g., on PR #835 ).

selectively exclude NOT_READY algorithms from copy_from_pyclean

---

.circleci/config.yml
appveyor.yml
tests/CMakeLists.txt
tests/test_kem_mem.c
tests/test_mem.py
tests/test_sig_mem.c
tests/tmp_store.c

enable Valgrind memory use testing

---

docs/algorithms/kem/sike.md
src/kem/sike/external/fpx.c
src/kem/sike/kem_sike.c

Integrated commit [566630](https://github.com/microsoft/PQCrypto-SIDH/commit/566630ed811011feb2e77cf7c26abdb2f946de04) from SIKE. Fixes issue #861.

Integrated SIKE Dec 2020 update.

---

.CMake/compiler_opts.cmake
.circleci/config.yml
README.md
src/CMakeLists.txt
src/common/CMakeLists.txt
src/common/common.c
src/common/common.h
tests/CMakeLists.txt
tests/system_info.c
tests/test_portability.py

add portability tests

---

docs/algorithms/sig/picnic.md
src/sig/picnic/external/CHANGELOG.md
src/sig/picnic/external/LICENSE
src/sig/picnic/external/README.md
src/sig/picnic/external/endian_compat.h
src/sig/picnic/external/kdf_shake.h
src/sig/picnic/external/macros.h
src/sig/picnic/external/mpc_lowmc_impl.c.i
src/sig/picnic/external/mpc_lowmc_loop.c.i
src/sig/picnic/external/mpc_lowmc_loop_partial.c.i
src/sig/picnic/external/mzd_additional.c
src/sig/picnic/external/picnic3_impl.c
src/sig/picnic/external/picnic3_tree.c
src/sig/picnic/external/picnic_impl.c
src/sig/picnic/external/picnic_instances.h
src/sig/picnic/external/sha3/s390_cpacf.h
src/sig/picnic/sig_picnic.c

Updated picnic from tag v3.0.3 to v3.0.4 ([github compare](https://github.com/IAIK/Picnic/compare/1797ab...v3.0.4)), which include clean-ups.

Picnic Dec 2020 update.

---

.circleci/config.yml

remove docker auth for now

---

.circleci/config.yml
src/common/rand/rand.c

- Fixes #895
- Upgrades CCI to ubuntu 20

Mb randloop

---

docs/algorithms/kem/kyber.md
scripts/copy_from_upstream/copy_from_upstream.yml
src/kem/kyber/CMakeLists.txt
src/kem/kyber/kem_kyber_1024.c
src/kem/kyber/kem_kyber_1024_90s.c
src/kem/kyber/kem_kyber_512_90s.c
src/kem/kyber/kem_kyber_768.c

Kyber768 ref dependencies (#899)

---

tests/helpers.py
tests/test_code_conventions.py

This PR switches our helpers.run_subprocess function back to using Python's `subprocess.run`. It also includes a pure python implementation of test_free which serves as an alternative fix for #852. The previous fix for #852 in commit 346305fc added a timeout to our subprocess calls which we've been hitting in CI.
The timeout was a less-than-ideal solution for killing long running jobs since it is based on wall-clock time.

Switch back to subprocess.run

---

.CMake/alg_support.cmake
.CMake/compiler_opts.cmake
.circleci/config.yml
CMakeLists.txt

This adds an option to build only the default KEM and Signature scheme. For example, with this patch, if you want to build liboqs with only the Kyber512 and Dilithium2 algorithms you can use:
```
cmake -GNinja -DOQS_MINIMAL_BUILD=ON -DOQS_KEM_DEFAULT=OQS_KEM_alg_kyber_512 -DOQS_SIG_DEFAULT=OQS_SIG_alg_dilithium_2 ..
```
This will build the exact match for the default kem and sig and also any "_aesni" or "_avx2" implementations that are supported by the platform.
Opening this PR, at @baentsch's recommendation, for discussion about whether this is a useful feature / what else we would like it to do.
**Edit:** Tacking on proposed CI workflow from https://github.com/open-quantum-safe/liboqs/issues/907#issuecomment-777771017

Add OQS_MINIMAL_BUILD option and redefine CI workflow

---

src/common/sha3/keccak4x/KeccakP-1600-times4-SIMD256.c

There are two uint64_t arrays declared in `KeccakP-1600-times4-SIMD256.c` that are accessed using `_mm256_load_si256` but are not guaranteed to have 32 byte alignment.
```c
#define CONST256(a) _mm256_load_si256((const V256 *) &(a))
[...]
#define ROL64in256_8(d, a) d = _mm256_shuffle_epi8(a, CONST256(rho8))
#define ROL64in256_56(d, a) d = _mm256_shuffle_epi8(a, CONST256(rho56))
static const UINT64 rho8[4] = {0x0605040302010007, 0x0E0D0C0B0A09080F, 0x1615141312111017, 0x1E1D1C1B1A19181F};
static const UINT64 rho56[4] = {0x0007060504030201, 0x080F0E0D0C0B0A09, 0x1017161514131211, 0x181F1E1D1C1B1A19};
```
This is (likely) the undefined behaviour detected by UBSan in #791.
The first commit of this PR fixes the alignment with a union type. The second commit backports some minor changes to the …

Fix undefined behaviour in keccak4x

---

src/sig/picnic/CMakeLists.txt

Temporary fix for #921 until #922 lands

Compile Picnic's Keccak with NO_MISALIGNED_ACCESSES

---

tests/constant_time/kem/passes/mceliece-348864
tests/constant_time/kem/passes/mceliece-348864f
tests/constant_time/kem/passes/mceliece-460896
tests/constant_time/kem/passes/mceliece-460896f
tests/constant_time/kem/passes/mceliece-6688128
tests/constant_time/kem/passes/mceliece-6688128f
tests/constant_time/kem/passes/mceliece-6960119
tests/constant_time/kem/passes/mceliece-6960119f
tests/constant_time/kem/passes/mceliece-8192128
tests/constant_time/kem/passes/mceliece-8192128f
tests/constant_time/kem/passes/mceliece-sk_gen

Valgrind reports no new instances of suspected non-constant time behaviour in the AVX McEliece code. The warnings that are issued are identical (modulo line number) to the warnings that are issued for the "vec" implementation. All of these are false positives.

Valgrind suppression files for AVX McEliece

---

src/kem/kem.h
src/sig/sig.h

They made a reference to example files that had been moved at some point.

Fix small error in comments of kem.h and sig.h

---

.circleci/config.yml
scripts/copy_from_upstream/patches/pqcrystals-dilithium-avx2-shake.patch
src/sig/dilithium/pqcrystals-dilithium_dilithium2-aes_avx2/poly.c
src/sig/dilithium/pqcrystals-dilithium_dilithium2-aes_avx2/symmetric.h
src/sig/dilithium/pqcrystals-dilithium_dilithium2_avx2/poly.c
src/sig/dilithium/pqcrystals-dilithium_dilithium2_avx2/symmetric.h
src/sig/dilithium/pqcrystals-dilithium_dilithium3-aes_avx2/poly.c
src/sig/dilithium/pqcrystals-dilithium_dilithium3-aes_avx2/symmetric.h
src/sig/dilithium/pqcrystals-dilithium_dilithium3_avx2/poly.c
src/sig/dilithium/pqcrystals-dilithium_dilithium3_avx2/symmetric.h
src/sig/dilithium/pqcrystals-dilithium_dilithium_5-aes_avx2/poly.c
src/sig/dilithium/pqcrystals-dilithium_dilithium_5-aes_avx2/symmetric.h
src/sig/dilithium/pqcrystals-dilithium_dilithium_5_avx2/poly.c
src/sig/dilithium/pqcrystals-dilithium_dilithium_5_avx2/symmetric.h

A recent address-sanitizer [run](https://app.circleci.com/pipelines/github/open-quantum-safe/liboqs/1377/workflows/3ec747c5-0774-42a5-b071-da0506d1dfbd/jobs/13636) noticed that a shake context was not getting freed in Dilithium 3.

Fix shake context leak in Dilithium

---

.CMake/alg_support.cmake
scripts/copy_from_xkcp/CMakeLists.txt
scripts/copy_from_xkcp/package.sh
scripts/copy_from_xkcp/patches/lib_low_KeccakP-1600-times4_AVX2_KeccakP-1600-times4-SIMD256.c
scripts/copy_from_xkcp/patches/lib_low_KeccakP-1600-times4_AVX2_KeccakP-1600-times4-SnP.h
scripts/copy_from_xkcp/patches/lib_low_KeccakP-1600-times4_fallback-on1_KeccakP-1600-times4-SnP.h
scripts/copy_from_xkcp/patches/lib_low_KeccakP-1600-times4_fallback-on1_KeccakP-1600-times4-on1.c
scripts/copy_from_xkcp/patches/lib_low_KeccakP-1600_AVX2_KeccakP-1600-AVX2.s
scripts/copy_from_xkcp/patches/lib_low_KeccakP-1600_AVX2_KeccakP-1600-SnP.h
scripts/copy_from_xkcp/patches/lib_low_KeccakP-1600_plain-64bits_KeccakP-1600-SnP.h
scripts/copy_from_xkcp/patches/lib_low_KeccakP-1600_plain-64bits_KeccakP-1600-opt64.c
scripts/copy_from_xkcp/patches/lib_low_common_PlSnP-Fallback.inc
src/common/CMakeLists.txt
src/common/sha3/xkcp_dispatch.h
src/common/sha3/xkcp_low/CMakeLists.txt
src/common/sha3/xkcp_low/KeccakP-1600/avx2/KeccakP-1600-AVX2.S
src/common/sha3/xkcp_low/KeccakP-1600/avx2/KeccakP-1600-SnP.h
src/common/sha3/xkcp_low/KeccakP-1600/plain-64bits/KeccakP-1600-SnP.h
src/common/sha3/xkcp_low/KeccakP-1600/plain-64bits/KeccakP-1600-opt64.c
src/common/sha3/xkcp_low/KeccakP-1600times4/avx2/KeccakP-1600-times4-SIMD256.c
src/common/sha3/xkcp_low/KeccakP-1600times4/avx2/KeccakP-1600-times4-SnP.h
src/common/sha3/xkcp_low/KeccakP-1600times4/serial/KeccakP-1600-times4-SnP.h
src/common/sha3/xkcp_low/KeccakP-1600times4/serial/KeccakP-1600-times4-on1.c
src/common/sha3/xkcp_low/KeccakP-1600times4/serial/PlSnP-Fallback.inc
src/common/sha3/xkcp_sha3.c
src/common/sha3/xkcp_sha3x4.c

This PR allows us to use platform-optimized implementations of SHA3 in dist builds.
Most of the work here is in giving each KeccakP1600 / KeccakP1600-times4 implementation its own namespace. 
The dispatching is done with indirect function calls. The first time a sha3 context is initialized we check for CPU features and update a few function pointers. After that there's no overhead.

Add SHA3 call dispatching

---

src/oqsconfig.h.cmake

Fixes a missing #define, which is causing the loss of performance for Frodo and Kyber on https://github.com/open-quantum-safe/profiling/issues/47.

Add missing OQS_ENABLE_SHA3_xkcp_low_avx2 line to oqsconfig.h

---

src/common/aes/aes.c

Don't do CPU feature detection every time inside a loop, just do it once. 
* [No] Does this PR change the the list of algorithms available -- either adding, removing, or renaming?  (If so, PRs in OQS-OpenSSL, OQS-BoringSSL, and OQS-OpenSSH will also be required by the time this is merged.)

Don't do feature detection inside a tight loop

---

scripts/copy_from_xkcp/patches/lib_low_KeccakP-1600-times4_AVX2_KeccakP-1600-times4-SIMD256.c
src/common/sha3/xkcp_low/KeccakP-1600times4/avx2/KeccakP-1600-times4-SIMD256.c

Schemes using sha3x4 showed some modest [loss of performance](https://github.com/open-quantum-safe/profiling/issues/47) on Alpine linux with our new sha3 implementations.
It turns out that musl libc has a slow implementation of memmove, and a single memmove that I added while removing undefined behaviour from the avx2 sha3x4 implementation was the culprit. Switching this particular memmove to a memcpy does not re-introduce any undefined behaviour.
This PR restores the lost performance in my local tests with our profiling container.
IMO we should still switch to a different libc for benchmarking.

Improve sha3x4 performance with musl libc

---

src/common/aes/aes.c
src/common/aes/aes128_ni.c
src/common/aes/aes256_ni.c
src/common/aes/aes_c.c
src/common/aes/aes_local.h

Fixes #949. 
* [No] Does this PR change the the list of algorithms available -- either adding, removing, or renaming?  (If so, PRs in OQS-OpenSSL, OQS-BoringSSL, and OQS-OpenSSH will also be required by the time this is merged.)

Switch AES C implementation to PQClean's

---

src/common/common.h

UEFI/EDKII used openssl as crypto lib with OPENSSL_SYS_UEFI.
This patch adds OQS_SYS_UEFI macro in liboqs to indicate special build in UEFI/EDKII.
With this patch, we can start building liboqs in UEFI/EDKII.
For algorithm specific patches, we will submit one by one later.
Signed-off-by: Jiewen Yao <jiewen.yao@intel.com>

Enable liboqs build in UEFI/EDKII.

---

src/common/CMakeLists.txt
src/common/rand/rand.c

Our `common/rand/rand.c` has two Linux/macOS implementations of OQS_randombytes_system. One uses the getrandom syscall through the getentropy interface. The other reads from /dev/urandom.
The getentropy-based implementation fails to respect the 256 byte length limit on getentropy calls and hangs in an infinite loop when longer requests are made. It is also guarded by `#if defined(HAVE_GETENTROPY)`, and we aren't setting HAVE_GETENTROPY anywhere.
The other implementation uses C standard buffered I/O (fopen, fread) to /dev/urandom. There are problems with how it handles fopen and fread errors.
* On fopen failure it calls "delay" and then attempts to open the file again. The "delay" function is optimized out at -O2, and in general `fopen` errors are not recoverable.
* On fread failure …

Improve random sources when not using OpenSSL

---

tests/system_info.c

When running any test, the system information output should distinguish whether it displays CPU features present at compile-time **or** at run-time. Without this distinction, one can chase for hours problems caused in reality by missing CPU runtime features, e.g., in a cloud infrastructure sometimes offering those features and sometimes not offering them (one of the reasons for https://github.com/open-quantum-safe/profiling/issues/57 and manifested by [this output](https://github.com/open-quantum-safe/profiling/issues/57#issuecomment-831018780)).
```
```
)

output CPU feature CT/RT distinction

---

tests/test_kem.c

This changes the test_kem.c functions like those in PQClean:
* also prefix magic bytes for checking for out-of-bounds access
* use odd numbers for breaking alignment
Includes #985

Test without alignment

---

README.md

astyle is needed to be installed so the running of the tests succeeds. This just adds the needed dependency to be installed.
Does not resolved any issue.

astyle is needed to be installed on MacOS for run_tests to succeed

---

tests/test_kem.c
tests/test_sig.c

#986 inadvertently broke test_constant_time by using memcmp on some canaries in test_kem. This PR disables the canary checks when OQS_ENABLE_TEST_CONSTANT_TIME=ON.
More importantly, this PR adds canaries to test_sig. I followed #986 in using an odd length for the canaries in the hope of catching alignment bugs.

Add canaries around malloc'd regions in test_sig

---

tests/constant_time/kem/passes/hqc

This PR documents two false positives in test_constant_time for the AVX2 implementations of HQC.

tests/constant_time: update passes file for AVX2 impl of HQC [skip ci]

---

README.md

Build instruction & build parameter option documentation was duplicated in different places (this README and the Wiki) leading to duplicate maintenance effort and reader confusion. This PR streamlines this. Also added is some more guidance building for Windows.

documentation consolidation

---

src/common/sha3/xkcp_low/CMakeLists.txt

The sha3 CMakeLists.txt file was ignoring the OQS_ENABLE_SHA3_xkcp_low_avx2 option. This option is used to disable our AVX2 implementation of sha3 on Windows. Fixing this resolves one of several problems identified in #997.

Fix missing sha3 symbols for some Windows configurations

---

tests/constant_time/kem/passes/sike-compressed

Following a suggestion from @geovandro, I've refined the suppressions for SIKE to lower the risk of false negatives. I also updated a few line numbers. With these new suppressions, the SIKE code in our main branch and in #1008 both pass test_constant_time.

Update test_constant_time suppression files for SIKE

---

src/kem/bike/CMakeLists.txt

BIKE compilation fails when AVX512 and older CMake versions (like 3.10.*) are to be used.
Fixes #1032, resolves https://github.com/open-quantum-safe/boringssl/issues/64.

Make BIKE compile for older CMake versions when AVX512 is used

---

.CMake/alg_support.cmake
.circleci/config.yml
CMakeLists.txt
scripts/copy_from_upstream/src/kem/kem.h/algs_length.fragment
scripts/copy_from_upstream/src/sig/sig.h/algs_length.fragment
src/kem/kem.c
src/kem/kem.h
src/oqsconfig.h.cmake
src/sig/sig.c
src/sig/sig.h
tests/helpers.py

Begins to address #1043, retaining `OQS_MINIMAL_BUILD´ option: The latter now can be fed with a string of algorithms to be enabled, disabling all others.
Current state meant as intermediate state to check with @jschanck whether this approach is OK. If so, actual removal of DEFAULT algs will be added to this PR.

Removing default algs

---

README.md

Correcting reference removal in #1045.
This intentionally does not fix the equally incorrect https://github.com/open-quantum-safe/liboqs/blob/main/docs/algorithms/kem/bike.md assuming that will be fixed soon by #1030.

removing BIKE R2 from README

---

docs/.Doxyfile

Update Doxygen file

---

.travis.yml
README.md
tests/constant_time/sig/passes/dilithium
tests/constant_time/sig/passes/dilithium-aes-avx2

(1)
Simple TravisCI integration for ppc64le
(2)
Minor suppression file update for Dilithium after a constant-time check on ppc64le (see https://github.com/open-quantum-safe/liboqs/pull/1037):
(i) two line numbers changed, (ii) using explicit function name (fun:rej_uniform) for generic Dilithium
The CI log with reports is available here: [ppc64le.txt](https://github.com/open-quantum-safe/liboqs/files/6733709/ppc64le.txt)
The SPHINCS+ reports are documented separately in #1038.
The reported issues (except #1038) should also be reproducible using the `constant-time-x64-extensions` / `constant-time-x64` circleci jobs. After this fix, the constant-time checks pass on x86_64 / ppc64le, except BIKE that will have to be handled separately.

TravisCI for ppc64le and suppression file update for Dilithium

---

src/common/common.h

The UNUSED macro in common.h is not actually being used in the liboqs codebase anymore, so it can be removed. This also reduces risk of namespace conflict between macros defined via oqs.h and other application.
As suggested by @Martyrshot.

Remove UNUSED macro from OQS API

---

src/kem/bike/CMakeLists.txt
src/kem/bike/additional_r3/decode_internal.h
src/kem/bike/additional_r3/gf2x_internal.h
src/kem/bike/additional_r3/sampling_internal.h

I encountered a BIKE build failure on a non-AVX512 platform. BIKE's run-time dispatch protects against calls to a AVX512-dependent function, but the reference to that AVX512-dependent function is present despite that function not being compiled, which was leading to a linker error.
@dkostic Can you review?

Compile-time guard for some BIKE AVX2 and AVX512 code

---

.CMake/detect_gcc_clang_intrinsics.c
tests/system_info.c

This pr fixes an issue for apple silicon compile-time feature detection.
Replaces #1073.

Fix a bug where intrinsics were ignored when compiling for apple silicon

---

.circleci/config.yml
.github/workflows/linux.yml
.travis.yml
appveyor.yml

In hopes of partially alleviating pressure on our CircleCI quota as per #1025, this PR switches some jobs to use Github Actions rather than CircleCI.  In particular, I've started off with more "standalone" type jobs, which include:
- alpine (2 jobs - with OpenSSL and without)
- address sanitizer (1 job) (currently disabled until #1067 lands)
- ARM emulation jobs (1 job - armhf)
Nothing stops us from moving other jobs over as well, such as the main Ubuntu x86_64 and i386 jobs, or the macOS jobs, or even the Windows jobs.  But I wanted to get initial feedback and discussion of strategy.  This currently doesn't affect triggering of downstream jobs (when a merge to main happens) or Travis/Appveyor (except for filtering branches of the form `ghactionsonly-*` from being run on those other CI …

Use Github Actions for some CI

---

.circleci/config.yml

Fixes #1076: Run those tests once a week, Sunday midnight

fixing #1076

---

README.md

I was trying to build the .NET (C#) wrapper project (liboqs-dotnet) and its README referenced this repo/README to build the oqs shared library but I noticed the README only mentioned that a static library was built. The Golang wrapper did have instructions on how to do so, so for consistency and benefit to future readers, I updated this repo's one too.
No
* [ no] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [ no] Does this PR change the the list of algorithms available -- either adding, removing, or renaming?  (If so, PRs in OQS-OpenSSL, OQS-BoringSSL, and OQS-OpenSSH will also be required by the time this is merged.)

Add instructions on how to build shared/dynamic library to the README

---

docs/algorithms/kem/sike.md
docs/algorithms/kem/sike.yml
src/kem/sike/external/P434/AMD64/fp_x64.c
src/kem/sike/external/P434/ARM64/fp_arm64.c
src/kem/sike/external/P434/generic/fp_generic.c
src/kem/sike/external/P503/AMD64/fp_x64.c
src/kem/sike/external/P503/ARM64/fp_arm64.c
src/kem/sike/external/P503/generic/fp_generic.c
src/kem/sike/external/P610/AMD64/fp_x64.c
src/kem/sike/external/P610/ARM64/fp_arm64.c
src/kem/sike/external/P610/generic/fp_generic.c
src/kem/sike/external/P751/AMD64/fp_x64.c
src/kem/sike/external/P751/ARM64/fp_arm64.c
src/kem/sike/external/P751/generic/fp_generic.c
src/kem/sike/external/config.h
src/kem/sike/external/fpx.c
src/kem/sike/kem_sike.c

Updated SIKE to upstream commit effa60, addressing issue 1056: replaces `__inline` with `inline`; upstream also catches up to some changes already in OQS (for Apple M1 support).
Fixes #1056.

Updated SIKE to latest upstream commit

---

tests/CMakeLists.txt
tests/helpers.py
tests/test_mem.py
tests/test_namespace.py

So far, all test executions were contingent upon the availability of the (hard-coded) build directory "build". This proves cumbersome if using differently named build directories, e.g., for different build options or build targets (e.g., `liboqs` binaries for openssh static build, openssl shared build, etc.).
This PR does away with this limitation, using the `cmake` variable `CMAKE_BINARY_DIR` instead.

enabling flexible build dir name in testing

---

.circleci/config.yml

This should allow regular optimized code constant-time testing to pass despite current Valgrind platform limitations.

run optimized constant time tests only on haswell

---

.circleci/config.yml

This should allow constant-time testing to pass despite some algorithms being very slow (we won't name them :).

increase constant time test timeout allowing slow runners to complete [skip ci]

---

.circleci/config.yml
tests/test_constant_time.py

Fixes #1087. [Release documentation](https://github.com/open-quantum-safe/liboqs/wiki/Release-process) also updated.

skip algorithms for constant_time tests

---

.gitignore
tests/test_kem_mem.c
tests/test_sig_mem.c
tests/test_spdx.sh
tests/tmp_store.c

Provides fix to #1090 and enhances/completes #1080. CI failures still due to #1035.

Enabling out-of-source build-and-test

---

tests/helpers.py

Removing unnecessary test addressing/resolving https://github.com/open-quantum-safe/liboqs/pull/1091#issuecomment-922370718

correct out-of-source build-and-test

---

.circleci/config.yml

Disables SPHINCS+-SHA* tests from weekly tests due to timeouts.
AppVeyor failure most likely transient: Does anyone know how to trigger a re-run of that CI system?

skip more SPHINCS algs from weekly testing

---

tests/test_constant_time.py

Skip non-enabled algs in constant time tests.
The current script depended on a `SKIP_ALGS` variable, that isn't documented and isn't set by cmake when using the `OQS_MINIMAL_BUILD ` build macro. I'm not sure if that code can safely replaced by the common helper check (as this PR does), or if it has a deeper purpose I don't understand. (@jschanck?)

Skip non-enabled algs in constant time tests

---

tests/constant_time/sig/passes/picnic3

Updated valgrind constant time exception for picnic, for new code and code that moved in the file (updated line numbers).
Fix #1118.

Updated valgrind constant time exception for picnic

---

tests/constant_time/sig/passes/picnic3

Added Keccak constant time exclusion for Picnic AVX2. Fix #1118.

Added Keccak constant time exclusion for Picnic AVX2

---

.circleci/config.yml

skip more ClassicMcEliece weekly CI constant time tests [skip ci]

---

tests/run_astyle.sh

Fixes #1129 (now also guarding against regressions).
Also, problematic files are highlighted better and advice is output what needs to be done on error.

more code style checks

---

tests/ds_benchmark.h
tests/speed_kem.c
tests/speed_sig.c
tests/test_aes.c

This pull request enables the use of ARMv8's performance monitoring unit (PMU) in the benchmarking script to allow for a more precise cycle count on that architecture when possible. It is enabled by the OQS_SPEED_USE_ARM_PMU compiler flag. Note that loading a kernel module (such as https://github.com/mupq/pqax#enable-access-to-performance-counters ) is required to access the PMU from user mode.

Enabling use of ARM PMU for benchmarking when compiler flag is enabled

---

tests/CMakeLists.txt
tests/speed_common.c

This adds a speed_common script, similar to speed_kem and speed_sig, but for benchmarking the encryption and hashing algorithms that `liboqs` uses. Specifically, it benchmarks AES128, AES256, SHA256, SHA384, SHA512, SHA3-256, SHA3-384, SHA3-512, SHA3-shake128, and SHA3-shake256. Currently it only benchmarks the main API of each of the hash algorithms, not the incremental version (that is something that could be added later if it's needed).
The script has a few options to change how it is run:
`--msglen n` : Each algorithm is benchmarked with a message length of `n` bytes (must be a multiple of 16 to benchmark AES)
`--outlen n` : For algorithms with variable-length output (e.g., shake128), specifies the output length.
`<alg>` : Only benchmark a specific algorithm.
Fulfills request in #1143

Adding a speed_common script to benchmark OQS AES and hash algorithms

---

src/common/pqclean_shims/nistseedexpander.c
src/common/pqclean_shims/nistseedexpander.h
src/common/rand/rand_nist.c

NIST copyright clarification

---

CMakeLists.txt
src/oqsconfig.h.cmake
tests/ds_benchmark.h
tests/speed_kem.c
tests/speed_sig.c
tests/test_aes.c

#1141 didn't merge to main, so this fixes that.

Option to use PMU for benchmarking on ARM

---

tests/ds_benchmark.h

- Fix bug in standard deviation calculation
- Cast values to protect against overflows (as suggested by https://github.com/open-quantum-safe/liboqs/pull/1141#issuecomment-989708501)
* [No] Does this PR change the the list of algorithms available -- either adding, removing, or renaming?  (If so, PRs in OQS-OpenSSL, OQS-BoringSSL, and OQS-OpenSSH will also be required by the time this is merged.)

Tweaks to benchmarking code

---

scripts/noregress.py
scripts/noregress.sh

This script uses code from `profiling` to compare execution performance between the current code and a `liboqs` release. It outputs only significant (>15%) deviations. It has been tested successfully on `x86_64` and `aarch64` platforms comparing `0.7.1-rc1` vs `0.7.0` and `0.6.0`. Documentation is available in [release process](https://github.com/open-quantum-safe/liboqs/wiki/Release-process#performance).

release performance regression test

---

docs/algorithms/sig/falcon.md
docs/algorithms/sig/falcon.yml

https://github.com/open-quantum-safe/liboqs/blob/main/docs/algorithms/sig/falcon.md states **license CC0-1.0**
But the license in the header file at https://falcon-sign.info/impl/falcon.h.html is  ** license MIT** , the same at https://github.com/PQClean/PQClean/blob/master/crypto_sign/falcon-1024/clean/LICENSE
No

docs: set license MIT to Falcon Signature

---

.circleci/config.yml

`oqs-provider` needs to get triggered on merges to `main` to avoid surprising build failures.

add trigger for oqs-provider CI

---

.circleci/config.yml

Upgrade XCode environment for OSX to evade CCI deprecation notice.

XCode update

---

appveyor_build.bat
docs/algorithms/sig/picnic.md
docs/algorithms/sig/picnic.yml

remove picnic from cygwin build

---

.github/workflows/weekly.yml

Tries to implement #1169. Shall replace [CCI weekly run](https://github.com/open-quantum-safe/liboqs/blob/5ea49c2a446945d6ddece9c0a11d931b7c3f040f/.circleci/config.yml#L368-L402) if this works OK for a few weeks.
AppVeyor still failing because of #1163

adding constant time test as weekly github action

---

.github/workflows/weekly.yml

Extending maximum weekly constant runtime test time to 2h.

extend weekly run timeout [skip ci]

---

.CMake/alg_support.cmake

Fixes #1179 (known failure due to #1178)

disable BIKE on all 32bitters except x86

---

.github/workflows/weekly.yml

A wonder occurred and the constant time tests all [ran and passed](https://github.com/open-quantum-safe/liboqs/actions/runs/1759247537). Now installing them for good on Sundays.

weekly job moved to Sunday [skip ci]

---

src/common/CMakeLists.txt
src/common/sha2/sha2_local.h

This PR resolves a build issue when using gcc11 on Darwin.
The issue is resolved by specifying the architecture version and explicitly enabling crypto extensions. After running `speed_common`, it appeared that there were no significant performance differences between armv8-a and armv8.5-a, so armv8-a was used to maximize compatibility.

Resolves an issue when building sha2 using arm crypto extensions with gcc11

---

docs/algorithms/sig/rainbow.md

adding warning re Rainbow to documentation [skip ci]

---

tests/test_code_conventions.py

Fixes #1195.
General question: Why is this `yamllint` test existing at all? It fails, has a TODO mark and is not listed as a build prerequisite -> Better to delete completely? Or create an issue to implement it properly?

skip yamllint test for good

---

src/kem/sike/external/ec_isogeny.c
tests/speed_common.c

In hopes of eventually closing #194, I ran clang scan-build and it found a few minor issues.  This PR deals with some of them, I'll create an issue for the rest.
scan-build can be run as follows:
```bash
cd liboqs
mkdir build-analyze && cd build-analyze
scan-build cmake -GNinja ..
scan-build ninja
```
On macOS, I don't know where Apple's version of scan-build is (it's not in the path), but you can do `brew install llvm@11` and then use `/usr/local/Cellar/llvm@11/11.1.0_4/bin/scan-build` (since brew doesn't add llvm's files to the path to avoid conflicting with the Apple versions).

Deal with some issues identified by clang scan-build

---

src/CMakeLists.txt
src/common/rand/rand.c

Building on iOS is currently broken (cf. #1217), due to the `rand` functionality attempting to include the `sys/random.h` header (which is not available on iOS).
This series allows building for iOS by:
- Using the `SecRandomCopyBytes` secure system randomness function when building for iOS, rather than using `getentropy` or reading from `urandom`
- This means we don't include the `sys/random.h` header when building for iOS
- Note that the CMake check for `getentropy` will already find that `getentropy` is not available on iOS, so otherwise (without this patch) on iOS we would be attempting to read from `urandom` (which is also not allowed on iOS)
- Links against the iOS `Security` "framework", when building for iOS
Fixes #1217

Use `SecRandomCopyBytes` for system randomness on iOS (to allow building on iOS)

---

scripts/copy_from_upstream/patches/pqcrystals-dilithium-avx2-shake-aes.patch
src/sig/dilithium/pqcrystals-dilithium_dilithium2_avx2/sign.c
src/sig/dilithium/pqcrystals-dilithium_dilithium2aes_avx2/sign.c
src/sig/dilithium/pqcrystals-dilithium_dilithium3_avx2/sign.c
src/sig/dilithium/pqcrystals-dilithium_dilithium3aes_avx2/sign.c
src/sig/dilithium/pqcrystals-dilithium_dilithium5_avx2/sign.c
src/sig/dilithium/pqcrystals-dilithium_dilithium5aes_avx2/sign.c

Adds a `aes256_ctx_release` in Dilithium-AES. Fixes a memory leak detected in #1234.
Updates sign.c patch and does copy_from_upstream.

Adds AES context release in Dilithium-AES / fix memory leak

---

docs/algorithms/sig/picnic.md
docs/algorithms/sig/picnic.yml
src/sig/picnic/external/lowmc.c.i
src/sig/picnic/external/picnic3_simulate.c.i
src/sig/picnic/external/picnic3_tree.c
src/sig/picnic/sig_picnic.c

This one should also fix the remaining scan-build warning.

Bump Picnic to 3.0.15

---

scripts/copy_from_upstream/patches/pqcrystals-dilithium-avx2-shake-aes.patch
src/sig/dilithium/pqcrystals-dilithium_dilithium2_avx2/sign.c
src/sig/dilithium/pqcrystals-dilithium_dilithium2aes_avx2/sign.c
src/sig/dilithium/pqcrystals-dilithium_dilithium3_avx2/sign.c
src/sig/dilithium/pqcrystals-dilithium_dilithium3aes_avx2/sign.c
src/sig/dilithium/pqcrystals-dilithium_dilithium5_avx2/sign.c
src/sig/dilithium/pqcrystals-dilithium_dilithium5aes_avx2/sign.c

Adds a aes256_ctx_release in Dilithium-AES. Fixes remaining memory leak detected in https://github.com/open-quantum-safe/liboqs/pull/1234.
Updates sign.c patch and does copy_from_upstream.

Updated Dilithium sign.c patch with AES context release (2)

---

.circleci/config.yml
docs/algorithms/kem/kyber.md

Fixes #1239. Avoid recurrence of #1212 ~(which arguably should be re-opened)~.
@dstebila : Please decide how/when to merge this. My suggestion would be after @sebastinas and @bhess had a chance to review the [run log](https://circleci.com/api/v1.1/project/github/open-quantum-safe/liboqs/17515/output/103/0?file=true&allocation-id=62bb17df947e861ada3206ce-0-build%2F54D6229E) for the picnic and kyber issues listed.
* [no] Does this PR change the the list of algorithms available -- either adding, removing, or renaming?  (If so, PRs in OQS-OpenSSL, OQS-BoringSSL, and OQS-OpenSSH will also be …

adding scan-build test

---

.circleci/config.yml
docs/algorithms/kem/classic_mceliece.md
tests/run_astyle.sh
tests/test_leaks.py

Fixes #1213 -- excluding "Classic-McEliece-8192128" as it fails the memory leak test. Open to suggestions how to otherwise handle / document this failure: Draft PR until then.

adding memory leak testing

---

appveyor.yml

disable msys2 testing

---

README.md

Please kindly add valgrind as test dependencies in README.md. I am getting error when running the complete test suite without valgrind: 
> FileNotFoundError: [Errno 2] No such file or directory: 'valgrind'
>
> /usr/lib/python3.8/subprocess.py:1704: FileNotFoundError
> ----------------------------- Captured stdout call -----------------------------
> ID=ubuntu
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> Linux bb-ubuntu-68 5.13.0-51-generic #58~20.04.1-Ubuntu SMP Tue Jun 14 11:29:12 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
> . > valgrind -s --error-exitcode=1 --leak-check=full --show-leak-kinds=all …

docs: Add valgrind as test dependencies in README.md

---

tests/dump_alg_info.c

* Fix memory leak detected by valgrind
This commit fixed the memory leak problem inside the tests directory.
No.
No.

Deal with the issue identified by valgrind

---

src/kem/hqc/pqclean_hqc-rmrs-128_avx2/reed_muller.c
src/kem/hqc/pqclean_hqc-rmrs-192_avx2/reed_muller.c
src/kem/hqc/pqclean_hqc-rmrs-256_avx2/reed_muller.c

Make index variable `i` immediate by unrolling the loop. This is just lucky guess that's worked, because similar in function intrinsic `_mm256_extract_epi16` requires immediate value for its index.
Workaround to the (perhaps) GCC 12 bug:
```
In function 'find_peaks',
inlined from 'PQCLEAN_HQCRMRS192_AVX2_reed_muller_decode' at /usr/src/RPM/BUILD/liboqs-0.7.1/src/kem/hqc/pqclean_hqc-rmrs-192_avx2/reed_muller.c:387:18:
/usr/src/RPM/BUILD/liboqs-0.7.1/src/kem/hqc/pqclean_hqc-rmrs-192_avx2/reed_muller.c:336:44: error: 'tmp' is used uninitialized [-Werror=uninitialized]
336 |         result |= mask & ((uint16_t *)&tmp)[i];
|                          ~~~~~~~~~~~~~~~~~~^~~
/usr/src/RPM/BUILD/liboqs-0.7.1/src/kem/hqc/pqclean_hqc-rmrs-192_avx2/reed_muller.c: In function …
```

pqclean_hqc: Fix build on GCC-12

---

.github/pull_request_template.md

Add explicit oqs-provider and API-breakage warning.

update PR template to include oqs-provider (OSSL dependency) [skip ci]

---

docs/algorithms/sig/picnic.md
docs/algorithms/sig/picnic.yml
src/sig/picnic/external/bitstream.h
src/sig/picnic/external/lowmc_impl_partial.c.i
src/sig/picnic/external/macros.h
src/sig/picnic/external/mpc_lowmc.h
src/sig/picnic/external/mzd_additional.h
src/sig/picnic/external/simd.h
src/sig/picnic/sig_picnic.c

This update fixes alignment issues when built with MSVC.

Update to Picnic 3.0.16 (fixes #1253)

---

src/common/common.c
src/common/common.h
tests/test_kem.c
tests/test_sig.c

Provide a mechanism to retrieve at runtime, e.g., in a shared library, the current library version string. For use e.g. in language wrappers to display the true library version wrapped.
* [no] Does this PR change the the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in [oqs-provider](https://github.com/open-quantum-safe/oqs-provider), [OQS-OpenSSL](https://github.com/open-quantum-safe/openssl), [OQS-BoringSSL](https://github.com/open-quantum-safe/boringssl), and …

adding library version retrieval function

---

tests/constant_time/sig/passes/dilithium-avx2

Fixes #1279, completes #1221. 
Line numbers have been changed by manually comparing the known-good, pre-#1221 `valgrind` pass file with the pre-#1221 dilithium-avx code and manually checking where the corresponding lines are located in the current, post-#1221 dilithium-avx2 code. 
* [no] Does this PR change the the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in [oqs-provider](https://github.com/open-quantum-safe/oqs-provider), [OQS-OpenSSL](https://github.com/open-quantum-safe/openssl), …

fixup dilithium-avx2 valgrind test file

---

.github/workflows/linux.yml
tests/helpers.py

We have `SKIP_ALGS` available on `test_constant_time.py` but nowhere else.  This adds it to the general test filter alongside `SKIP_TESTS`.  (The method I've used to add it is somewhat brutish, but seems to do the job.)

Add option to all pytests to skip particular algorithms

---

docs/algorithms/sig/picnic.md
docs/algorithms/sig/picnic.yml
src/sig/picnic/external/lowmc.c
src/sig/picnic/external/lowmc_pars.h
src/sig/picnic/external/mpc_lowmc.c
src/sig/picnic/external/picnic3_impl.c
src/sig/picnic/external/picnic3_simulate.c
src/sig/picnic/external/picnic3_simulate.c.i
src/sig/picnic/external/picnic3_types.c
src/sig/picnic/external/picnic3_types.h
src/sig/picnic/external/picnic_impl.c
src/sig/picnic/sig_picnic.c
tests/constant_time/sig/passes/picnic
tests/constant_time/sig/passes/picnic3

This is the Picnic update for #1278.

Update to Picnic 3.0.17

---

docs/algorithms/kem/hqc.md

As an alternative to resolving #995 this PR documents the HQC issue for the 0.7.2 release. 
The text will be automatically removed when the next `copy_from_upstream.py` run occurs.
* [no] Does this PR change the the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in [oqs-provider](https://github.com/open-quantum-safe/oqs-provider), [OQS-OpenSSL](https://github.com/open-quantum-safe/openssl), [OQS-BoringSSL](https://github.com/open-quantum-safe/boringssl), and [OQS-OpenSSH](https://github.com/open-quantum-safe/openssh) …

add warning about HQC [skip ci]

---

scripts/copy_from_upstream/requirements.txt

The script `scripts/update_docs_from_yaml.py` is using the python package
`tabulate`. It is missing from the `requirements.txt` file.
This PR adds it the the `requirements.txt` file.
~* [ ] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)~
~* [ ] Does this PR change the the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in [oqs-provider](https://github.com/open-quantum-safe/oqs-provider), [OQS-OpenSSL](https://github.com/open-quantum-safe/openssl), [OQS-BoringSSL](https://github.com/open-quantum-safe/boringssl), and …

Add missing requirements to the requirements.txt

---

src/sig/picnic/external/cpu.h

This change addresses the Picnic part of #1296.

Fix typo in Picnic's NEON detection

---

.CMake/compiler_opts.cmake

ARM32 gcc12 build workaround

---

src/common/CMakeLists.txt
src/common/common.c

There are two parts to this PR. The first one adds checks for `aligned_alloc` and friends and uses whatever is available. The second part fixes the check for `memset_s` (via cmake and Annex K support) and also uses `explicit_bzero` if available. 
* [no] Does this PR change the the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in [oqs-provider](https://github.com/open-quantum-safe/oqs-provider), [OQS-OpenSSL](https://github.com/open-quantum-safe/openssl), [OQS-BoringSSL](https://github.com/open-quantum-safe/boringssl), …

Fallback code for `aligned_alloc` and use of `explicit_bzero`

---

src/sig/sig.h
tests/speed_sig.c

addressing sig length questions

---

src/common/sha3/xkcp_sha3.c
src/common/sha3/xkcp_sha3x4.c

Suppose a user of the incremental SHA3 API absorbs 10 bytes, and then absorbs 2^64 - 10 bytes. At the beginning of the second `keccak_inc_absorb` call, the 25th element of the Keccak state is equal to 10, and there is a uint64_t overflow in
```
if (s[25] && mlen + s[25] >= r)
```
which causes the branch to be skipped. Later code assumes that `mlen >= r` implies that `s[25] = 0`, and calls
```
(*Keccak_AddBytes_ptr)(s, m, 0, r);
```
with third argument `0` instead of `s[25]`. This call modifies the wrong elements of the Keccak state, which leads to an incorrect result.
I went looking for bugs of this form because of CVE-2022-37454, but this one is not a security concern. It is also largely theoretical since it involves processing 2^64 bytes.

Integer overflow leading to incorrect SHA3 computation

---

docs/algorithms/kem/kyber.md
docs/algorithms/kem/kyber.yml
docs/algorithms/sig/dilithium.md
docs/algorithms/sig/dilithium.yml
scripts/copy_from_upstream/copy_from_upstream.yml
src/kem/kyber/pqcrystals-kyber_kyber1024-90s_ref/poly.h
src/kem/kyber/pqcrystals-kyber_kyber1024_ref/poly.h
src/kem/kyber/pqcrystals-kyber_kyber512-90s_ref/poly.h
src/kem/kyber/pqcrystals-kyber_kyber512_ref/poly.h
src/kem/kyber/pqcrystals-kyber_kyber768-90s_ref/poly.h
src/kem/kyber/pqcrystals-kyber_kyber768_ref/poly.h
src/sig/dilithium/pqcrystals-dilithium_dilithium2_avx2/LICENSE
src/sig/dilithium/pqcrystals-dilithium_dilithium2_ref/LICENSE
src/sig/dilithium/pqcrystals-dilithium_dilithium2aes_avx2/LICENSE
src/sig/dilithium/pqcrystals-dilithium_dilithium2aes_ref/LICENSE
src/sig/dilithium/pqcrystals-dilithium_dilithium3_avx2/LICENSE
src/sig/dilithium/pqcrystals-dilithium_dilithium3_ref/LICENSE
src/sig/dilithium/pqcrystals-dilithium_dilithium3aes_avx2/LICENSE
src/sig/dilithium/pqcrystals-dilithium_dilithium3aes_ref/LICENSE
src/sig/dilithium/pqcrystals-dilithium_dilithium5_avx2/LICENSE
src/sig/dilithium/pqcrystals-dilithium_dilithium5_ref/LICENSE
src/sig/dilithium/pqcrystals-dilithium_dilithium5aes_avx2/LICENSE
src/sig/dilithium/pqcrystals-dilithium_dilithium5aes_ref/LICENSE

Updates Kyber and Dilithium from upstream, see https://github.com/open-quantum-safe/liboqs/issues/1245#issuecomment-1319218926
Dilithium adds Apache2-License. Kyber fixes a code comment. No code changes. No interop changes.

update Kyber and Dilithium from upstream

---

tests/test_leaks.py

valgrind reported errors on several unit tests.  A search suggested adding the option:
--vex-guest-max-insns=25
to the valgrind command.
Resolves valgrind errors in unit test.

add valgrind option

---

.github/workflows/linux.yml
src/common/sha3/ossl_sha3x4.c

Fixes an issue in the OpenSSL sha3x4 code for context reset: `OQS_SHA3_shake128_x4_inc_ctx_reset` and `OQS_SHA3_shake256_x4_inc_ctx_reset`.
The context needs to be initialized again before use. Note the different behavior between the sha3(x4) and sha3(x1) implementations:
https://github.com/open-quantum-safe/liboqs/blob/2e42595804242d1e24e04f0f770a348c0c22313b/src/common/sha3/ossl_sha3x4.c#L119-L126
.. and
https://github.com/open-quantum-safe/liboqs/blob/2e42595804242d1e24e04f0f770a348c0c22313b/src/common/sha3/ossl_sha3.c#L222-L227
The issue can be reproduced with `-DOQS_USE_SHA3_OPENSSL=ON`, see https://github.com/open-quantum-safe/liboqs/issues/1338. It causes Kyber and Dilithium to fail.
The option seems to have never been part of a CI test, so never detected.
Fixes #1338.

fix: initialize context after reset in ossl_sha3x4

---

.CMake/alg_support.cmake
.circleci/config.yml
.github/workflows/linux.yml
CONFIGURE.md
README.md
appveyor.yml
appveyor_build.bat
docs/.Doxyfile
tests/example_kem.c
tests/example_sig.c

This reverts commit 9ba752ea9b0b4db375e21d2b27a16ed1de30e2be as not all downstream projects can handle limitation to NIST standardized algorithm set. 
A related PR is #1350 to resolve CCI failures. The proposed merge order is this PR first, then #1350.
* [yes -- reverting back to previous behaviour] Does this PR change the the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in [oqs-provider](https://github.com/open-quantum-safe/oqs-provider), [OQS-OpenSSL](https://github.com/open-quantum-safe/openssl), …

Revert "Enable algorithm filtering (#1333)"

---

.circleci/config.yml

This follows https://github.com/open-quantum-safe/ci-containers/pull/65 and unblocks CI failures.
Suggested to merge after #1351 
* [no] Does this PR change the the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in [oqs-provider](https://github.com/open-quantum-safe/oqs-provider), [OQS-OpenSSL](https://github.com/open-quantum-safe/openssl), [OQS-BoringSSL](https://github.com/open-quantum-safe/boringssl), and [OQS-OpenSSH](https://github.com/open-quantum-safe/openssh) will also need to be ready for review and merge by …

llvm15 update

---

CONFIGURE.md
scripts/doxyfy.py
scripts/run_doxygen.sh

Fix Doxygen Markdown failures

---

.github/workflows/linux.yml

Fixes #1340
@dstebila @xvzcf This PR also re-activated a test that was commented to be inactive until …

adding OpenSSL3 test; activating sanitizer test

---

appveyor.yml

Reverts #1243, enhancing Windows testing again.

re-enabling msys2 testing after picnic is gone

---

.CMake/compiler_opts.cmake
.circleci/config.yml
.github/workflows/linux.yml
CMakeLists.txt
CONFIGURE.md
src/kem/kyber/kem_kyber_512.c

As discussed in https://github.com/open-quantum-safe/liboqs/issues/1375#issuecomment-1412379440.
An initial CI error is intentional to test the feature. Will follow up with a correction (removal of unused variable).
* [no] Does this PR change the the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in [oqs-provider](https://github.com/open-quantum-safe/oqs-provider), [OQS-OpenSSL](https://github.com/open-quantum-safe/openssl), [OQS-BoringSSL](https://github.com/open-quantum-safe/boringssl), and …

compiler future-proofing Release builds

---

.circleci/config.yml
.github/workflows/linux.yml
tests/speed_kem.c
tests/speed_sig.c
tests/test_speed.py

Running `./tests/speed_sig Falcon-1024` with this new code reliably reproduces #1390 and could unearth similar such errors in the future -- ~when~ now added to CI: ~Feedback as to whether we should do this welcome: Would complete this PR with KEM-equivalent and github CI tests then~.
* [no] Does this PR change the the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in [oqs-provider](https://github.com/open-quantum-safe/oqs-provider), [OQS-OpenSSL](https://github.com/open-quantum-safe/openssl), …

Add full-cycle speed test

---

tests/test_kem.c
tests/test_sig.c

correct free in test_kem/sig

---

README.md
docs/algorithms/kem/kyber.md
docs/algorithms/kem/kyber.yml
docs/algorithms/sig/dilithium.md
docs/algorithms/sig/dilithium.yml
docs/cbom.json
scripts/copy_from_upstream/copy_from_upstream.yml
src/kem/kyber/kem_kyber_512.c
src/kem/kyber/pqcrystals-kyber_kyber1024-90s_avx2/LICENSE
src/kem/kyber/pqcrystals-kyber_kyber1024-90s_ref/LICENSE
src/kem/kyber/pqcrystals-kyber_kyber1024_avx2/LICENSE
src/kem/kyber/pqcrystals-kyber_kyber1024_ref/LICENSE
src/kem/kyber/pqcrystals-kyber_kyber512-90s_avx2/LICENSE
src/kem/kyber/pqcrystals-kyber_kyber512-90s_ref/LICENSE
src/kem/kyber/pqcrystals-kyber_kyber512_avx2/LICENSE
src/kem/kyber/pqcrystals-kyber_kyber512_ref/LICENSE
src/kem/kyber/pqcrystals-kyber_kyber768-90s_avx2/LICENSE
src/kem/kyber/pqcrystals-kyber_kyber768-90s_ref/LICENSE
src/kem/kyber/pqcrystals-kyber_kyber768_avx2/LICENSE
src/kem/kyber/pqcrystals-kyber_kyber768_ref/LICENSE

- Pulls latest Kyber commit from upstream (pqcrystals)
- Updates readme with pqcrystals license information (CC0 or Apache-2.0)
Fixes #1402

Copy from upstream (Kyber), add pqcrystals-* licenses to README

---

.github/ISSUE_TEMPLATE/bug_report.md

Gives --particularly first time-- contributors some guidance as to which information is needed to check problems reported.
* [no] Does this PR change the the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in [oqs-provider](https://github.com/open-quantum-safe/oqs-provider), [OQS-OpenSSL](https://github.com/open-quantum-safe/openssl), [OQS-BoringSSL](https://github.com/open-quantum-safe/boringssl), and [OQS-OpenSSH](https://github.com/open-quantum-safe/openssh) will also need to be ready for review and merge by the …

adding issue template [skip ci]

---

.github/workflows/linux.yml
docs/cbom.json
scripts/copy_from_upstream/requirements.txt

Replaces #1404, adding testing for correct use of `copy_from_upstream`. Depends on https://github.com/open-quantum-safe/ci-containers/pull/66 landing.
* [no] Does this PR change the the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in [oqs-provider](https://github.com/open-quantum-safe/oqs-provider), [OQS-OpenSSL](https://github.com/open-quantum-safe/openssl), [OQS-BoringSSL](https://github.com/open-quantum-safe/boringssl), and [OQS-OpenSSH](https://github.com/open-quantum-safe/openssh) will also need to be ready for …

CI test copy_from_upstream

---

tests/constant_time/sig/passes/falcon_keygen

Constant-time tests for Falcon on AVX2 are failing as per https://github.com/open-quantum-safe/liboqs/actions/runs/4333882416/jobs/7567377140
This is due to line numbers changing slightly since the last revision.
* [No] Does this PR change the the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in [oqs-provider](https://github.com/open-quantum-safe/oqs-provider), [OQS-OpenSSL](https://github.com/open-quantum-safe/openssl), [OQS-BoringSSL](https://github.com/open-quantum-safe/boringssl), and …

Fix constant time failure for Falcon AVX2

---

src/CMakeLists.txt
src/liboqs.pc.in

Adds a basic pkgconfig file generation. The main motivation for this is to enable linking a system-provided liboqs library in liboqs-rust.
I have done a simple manual test by creating a Void Linux package template for liboqs, installing it and checking that pkg-config detects its presence.
I am not proficient in pkgconfig, but I tried to follow the style found in some existing C libraries.
Closes #1434

Generate and install pkgconfig file

---

.CMake/compiler_opts.cmake

This allows us to override it when used in tandem with OQS_STRICT_WARNINGS.
Closes #1432

Use CMake flag for -Werror

---

src/common/common.c

Introduced in Linux 4.15, which, I admit, was a while ago.

src/common/common.c (set_available_cpu_extensions): Cope without `HWCAP_SHA3'

---

.CMake/alg_support.cmake

Fix to https://github.com/open-quantum-safe/liboqs/issues/1452#issuecomment-1542743269: No OpenSSL logic must be available if none of the "piece part" OQS_OPENSSL-enablement defines are set.
* [no] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in [oqs-provider](https://github.com/open-quantum-safe/oqs-provider), [OQS-OpenSSL](https://github.com/open-quantum-safe/openssl), [OQS-BoringSSL](https://github.com/open-quantum-safe/boringssl), and …

disable OpenSSL if neither AES,SHA2, or SHA3 are OSSL-provided

---

.CMake/alg_support.cmake
src/common/aes/aes256_ni.c
src/common/aes/aes_c.c
src/common/aes/aes_ossl.c
src/common/common.h
src/common/ossl_helpers.c
src/common/sha2/sha2.h
src/common/sha2/sha2_ossl.c
tests/test_hash.c
tests/test_hash.py

Possibly fixes #1452. Fixes issues in #1420.
- Corrects SHA2 API documentation
- Checks all SHA2 OpenSSL API return values
- Fixes SHA384 and SHA512 incremental API implementations
- Corrects testing for these APIs
- Enhances test vectors to avoid re-occurrence of problem
* [yes] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [no] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in [oqs-provider](https://github.com/open-quantum-safe/oqs-provider), [OQS-OpenSSL](https://github.com/open-quantum-safe/openssl), …

Fixing OpenSSL SHA2 incremental API integration

---

src/common/ossl_helpers.c

Fixes #1462
* [no] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in [oqs-provider](https://github.com/open-quantum-safe/oqs-provider), [OQS-OpenSSL](https://github.com/open-quantum-safe/openssl), [OQS-BoringSSL](https://github.com/open-quantum-safe/boringssl), and [OQS-OpenSSH](https://github.com/open-quantum-safe/openssh) will also need to be ready for review and merge by the time this is merged.)

relax OpenSSL initialization error handling

---

src/common/common.c
src/common/ossl_helpers.c
src/common/ossl_helpers.h

Straw man proposal for improving #1463.
* [no] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in [oqs-provider](https://github.com/open-quantum-safe/oqs-provider), [OQS-OpenSSL](https://github.com/open-quantum-safe/openssl), [OQS-BoringSSL](https://github.com/open-quantum-safe/boringssl), and [OQS-OpenSSH](https://github.com/open-quantum-safe/openssh) will also need to be ready for review and merge by the time this is merged.)

once OSSL init

---

src/common/common.c

Fixes #1471 
* [no] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in [oqs-provider](https://github.com/open-quantum-safe/oqs-provider), [OQS-OpenSSL](https://github.com/open-quantum-safe/openssl), [OQS-BoringSSL](https://github.com/open-quantum-safe/boringssl), and [OQS-OpenSSH](https://github.com/open-quantum-safe/openssh) will also need to be ready for review and merge by the time this is merged.)

protect ossl cleanup from multithreading errors

---

tests/ds_benchmark.h

Don't use cycle counter on ARM32

---

src/liboqs.pc.in

Libdir is not always '/usr/lib' and its value is different between distributions and architectures. Set it from CMAKE_INSTALL_LIBDIR. Also, set includedir in a similar way.
Currently, this incorrect setting did not produce incorrect output by pkg-config --libs because pkg-config strips 'system library paths' form the output. But in non-standard build environments this may cause incorrect linking.
Issue: https://github.com/open-quantum-safe/liboqs/issues/1495

Fix libdir value in liboqs.pc

---

.github/workflows/linux.yml

In pursuit of https://github.com/open-quantum-safe/oqs-provider/issues/94 this PR prepares (for) binary releases (to be added to release packages, for example).
The binary is intentionally created to
- only contain the standardized algorithms ("STD")
- only use OpenSSL3 APIs (so it can seamlessly be integrated to ´oqsprovider´)
- be built shared (such as to permit independent `dpkg -i`(installs))
Suggestions for other setups welcome. Suggestions where (else) to store the artifact also welcome (www.openquantumsafe.org?)
* [no] Does this PR change the list of algorithms available -- either …

create deb package and retain as artifact

---

.circleci/config.yml

The liboqs-python repository recently adopted GitHub Actions for CI/CD instead of CircleCI (https://github.com/open-quantum-safe/liboqs-python/commit/f52b2650897b5b918b58d3c3d11cad79b6a2f219), breaking the existing code in liboqs to trigger the downstream project's pipelines. The trigger was removed entirely in https://github.com/open-quantum-safe/liboqs/pull/1498.
This PR adds a new trigger for the liboqs-python CI, in which the liboqs-python pipelines are started via a call to the GitHub API. Doing this requires a personal access token; this was issued to the oqs-bot machine user and stored in the $OQSBOT_GITHUB_ACTIONS variable in the [liboqs CircleCI environment](https://app.circleci.com/settings/project/github/open-quantum-safe/liboqs/environment-variables?return-to=https%3A%2F%2Fapp. …

Trigger liboqs-python CI via GitHub API

---

src/sig_stfl/sig_stfl.c
src/sig_stfl/sig_stfl.h
src/sig_stfl/xmss/sig_stfl_xmss.h
src/sig_stfl/xmss/sig_stfl_xmss_sha256_h10.c
tests/test_sig_stfl.c

Introduce stateful key data object to allow tracking variant specific keys.

Re-add OQS_SECRET_KEY

---

docs/algorithms/kem/bike.md
docs/algorithms/kem/bike.yml

Fixes #1504 
BIKE is not working on Windows. OQS doesn't test BIKE on Windows. This fixes the incorrect documentation. @dkostic FYI/comment before merge.
* [no] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in [oqs-provider](https://github.com/open-quantum-safe/oqs-provider), [OQS-OpenSSL](https://github.com/open-quantum-safe/openssl), [OQS-BoringSSL](https://github.com/open-quantum-safe/boringssl), and [OQS-OpenSSH](https://github.com/open-quantum-safe/openssh) will also need to be ready for …

update BIKE documentation

---

docs/algorithms/kem/classic_mceliece.md
docs/algorithms/kem/classic_mceliece.yml
docs/algorithms/kem/hqc.md
docs/algorithms/kem/hqc.yml
docs/algorithms/kem/kyber.md
docs/algorithms/kem/kyber.yml
docs/algorithms/sig/dilithium.md
docs/algorithms/sig/dilithium.yml
docs/algorithms/sig/falcon.md
docs/algorithms/sig/falcon.yml
docs/algorithms/sig/sphincs.md
docs/algorithms/sig/sphincs.yml
scripts/copy_from_upstream/copy_from_upstream.yml
src/sig/falcon/pqclean_falcon-1024_avx2/sign.c
src/sig/falcon/pqclean_falcon-512_avx2/sign.c

https://github.com/PQClean/PQClean/commit/c3abebf4ab1ff516ffa71e6337f06d898952c299
Fixes #1488.

Pull Falcon updates from PQClean

---

.circleci/config.yml

Upgrade outdated XCode in CCI. Fixes CCI testing.
* [no] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in [oqs-provider](https://github.com/open-quantum-safe/oqs-provider), [OQS-OpenSSL](https://github.com/open-quantum-safe/openssl), [OQS-BoringSSL](https://github.com/open-quantum-safe/boringssl), and [OQS-OpenSSH](https://github.com/open-quantum-safe/openssh) will also need to be ready for review and merge by the time this is merged.)

Bump XCode

---

src/sig_stfl/sig_stfl.c
src/sig_stfl/sig_stfl.h

Update stateful APIs to use OQS_SIG_STFL_SECRET_KEY struct.
This will cause a temporary build break until the cutover is complete.

Convert to use OQS_SIG_STFL_SECRET_KEY struct 

---

.github/workflows/linux.yml

Pursuing https://github.com/open-quantum-safe/liboqs/issues/1393#issuecomment-1693720285
~Not intended for merge.~
This PR's CI seems to show that #1393 is resolved. Now suggesting to merge this to keep "speed" testing for armhf activated to avoid regression.

re-enable armhf speed testing

---

src/sig_stfl/lms/sig_stfl_lms.c
src/sig_stfl/lms/sig_stfl_lms.h
src/sig_stfl/lms/sig_stfl_lms_functions.c
src/sig_stfl/lms/sig_stfl_lms_wrap.h
src/sig_stfl/sig_stfl.h
tests/kat_sig_stfl.c
tests/test_sig_stfl.c

LMS updated to use new SK API

---

src/CMakeLists.txt
src/common/rand/rand.c

On Apple platforms arc4random is always available and it never fails. This removes a possible failure mode of liboqs on Apple platforms with `getentropy()`.
The man page for `getentropy()` on MacOSX also discourages its use
```
However, it should be noted that getentropy() is primarily intended for use in the construction and seeding of userspace PRNGs like
arc4random(3) or CC_crypto(3).  Clients who simply require random data should use arc4random(3), CCRandomGenerateBytes() from
CC_crypto(3), or SecRandomCopyBytes() from the Security framework instead of getentropy() or random(4)
```
On iOS we currently use SecRandomCopyBytes() this requires linking to the Security framework and the call can fail. We have run into issues with this call failing so we propose using `arc4random_buf()` as …

Prefer arc4random on Apple platforms

---

.CMake/apple.cmake
.github/workflows/android.yml
.github/workflows/apple.yml
.github/workflows/linux.yml

Adds CI for Apple mobile platforms.
Unfortunately I'm not sure how to effectively run the tests within the emulator. Plus it will likely be incredibly flaky. I think we should compile test this until we can figure out how to better run the full suite of tests.

ci: add CI for apple mobile platforms

---

tests/CMakeLists.txt
tests/helpers.py

This aligns the output folder for tests much like other platforms.
Fixes #1555

build: Align VS test folder with all other Generators

---

src/sig_stfl/lms/sig_stfl_lms.c
src/sig_stfl/lms/sig_stfl_lms.h
src/sig_stfl/lms/sig_stfl_lms_functions.c
src/sig_stfl/sig_stfl.c
src/sig_stfl/sig_stfl.h
src/sig_stfl/xmss/sig_stfl_xmss.h
src/sig_stfl/xmss/sig_stfl_xmss_secret_key_functions.c
tests/test_sig_stfl.c

Added capability to write secret key to file.
1. Create secret key
2. Generate key pair and set app specific context associated with the secret key. This context is used when updating the secret key.
3. Secret key is updated after each sign operation.
4. App manages the context and deletes associated memory when the key is deleted

Stateful sigs secret key storage callback

---

.github/workflows/weekly.yml

Corrects errors in `.github/weekly.yml` to skip CI constant time tests for Classic McEliece.
* [No ] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)

Fix weekly.yml to skip McEliece

---

.github/workflows/weekly.yml

Due to a configuration error, our weekly constant-time tests only run with `OQS_OPT_TARGET=generic`. This PR enables the intended configuration of `OQS_OPT_TARGET=haswell` by setting `OQS_DIST_BUILD=OFF`.
Fixes #1566.

Enable extensions in constant-time tests

---

src/sig_stfl/lms/sig_stfl_lms.c
src/sig_stfl/lms/sig_stfl_lms_functions.c
src/sig_stfl/sig_stfl.c
src/sig_stfl/sig_stfl.h
tests/test_sig_stfl.c

This PR enables a way to apply a lock(mutex) to secret key objects thereby giving protection from simultaneous access.
Stateful Sig API now include functions to set locking/unlocking callbacks and an associated mutex.
The library can then lock/unlock the secret key during signature generation and other queries (signing and queries for the number of signing operations remaining).
These supplied callbacks are application/OS specific.

Na statful sig lock

---

tests/constant_time/kem/issues/classic-mceliece-348864
tests/constant_time/kem/issues/classic-mceliece-348864f
tests/constant_time/kem/issues/classic-mceliece-460896
tests/constant_time/kem/issues/classic-mceliece-460896f
tests/constant_time/kem/issues/classic-mceliece-6688128
tests/constant_time/kem/issues/classic-mceliece-6688128f
tests/constant_time/kem/issues/classic-mceliece-6960119
tests/constant_time/kem/issues/classic-mceliece-6960119f
tests/constant_time/kem/issues/classic-mceliece-8192128
tests/constant_time/kem/issues/classic-mceliece-8192128f

This documents additional constant time errors reported during testing for the `0.9.0-rc1` release. 

Update Classic McEliece supression files

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
SECURITY.md

Completes [Github community standard documentation](https://github.com/open-quantum-safe/liboqs/community).
Fixes #1563 
* [no] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in [oqs-provider](https://github.com/open-quantum-safe/oqs-provider), [OQS-OpenSSL](https://github.com/open-quantum-safe/openssl), [OQS-BoringSSL](https://github.com/open-quantum-safe/boringssl), and [OQS-OpenSSH](https://github.com/open-quantum-safe/openssh) will also need to be ready for review and merge by the time this …

add community standard documentation [skip ci]

---

src/sig_stfl/lms/sig_stfl_lms_functions.c
tests/test_sig_stfl.c

Query the number of signing operations a private key can handle in total as well as the number
of signing operations that has already been done..

Secret Key Query 

---

.github/pull_request_template.md
CONFIGURE.md
README.md

- Adds test requirement to PR template (for feature changes)
- Clarifies OpenSSL versions supported/recommended
- Removes oqs-openssl111 and oqs-boringssl from checklist below
* [no] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in [oqs-provider](https://github.com/open-quantum-safe/oqs-provider), [OQS-OpenSSL](https://github.com/open-quantum-safe/openssl), [OQS-BoringSSL](https://github.com/open-quantum-safe/boringssl), and [OQS-OpenSSH](https://github.com/open-quantum-safe/openssh) will also …

PR template update & OpenSSL clarification

---

.CMake/compiler_opts.cmake
src/oqsconfig.h.cmake
tests/test_kem.c
tests/test_sig.c

Precursor to #1549. Replace `OQS_USE_PTHREADS_IN_TESTS` with `CMAKE_USE_PTHREADS_INIT` to clean up the Threads inclusion and linking story.

Use CMAKE_USE_PTHREADS_INIT

---

README.md

This is a very small change so that `ninja gen_docs` works as expected.
Without this change, doxygen (at least, version 1.9.8) gives the following error:
> unable to resolve reference to '/liboqs/CONFIGURE.md' for \ref command
This makes `scripts/run_doxygen.sh` return exit code 1 instead of 0, and causes `ninja gen_docs` to fail

Add section to CONFIGURE.md link

---

src/common/CMakeLists.txt
src/common/sha3/xkcp_sha3.c
src/common/sha3/xkcp_sha3x4.c
tests/CMakeLists.txt

Fixes #1548.
Call Keccak_(X4_)Dispatch using pthread_once to ensure setting of global function pointers is atomic and done only once.

Call Keccak_(X4_)Dispatch with pthread_once

---

.github/workflows/linux.yml
src/CMakeLists.txt
tests/CMakeLists.txt

This fixes the ["strange MacOS" CI problem](https://github.com/open-quantum-safe/liboqs/pull/1585#issuecomment-1792422996): Conceptually it isn't quite unlogical that the object file of "kem.c" should be made available to the link command of `kat_kem` (even though it should be part of the library). Let's see what CI says about the other platforms now....

fix kat_kem linkage to make HQC PR pass CI

---

.CMake/cmake_uninstall.cmake.in
CMakeLists.txt
README.md

This closes for good the question [how to uninstall liboqs](https://github.com/orgs/open-quantum-safe/discussions/1536).
* [no] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in fully supported downstream projects dependent on these, i.e., [oqs-provider](https://github.com/open-quantum-safe/oqs-provider) and [OQS-OpenSSH](https://github.com/open-quantum-safe/openssh) will also need to be ready for review and merge by the time this is merged.)

add uninstall support

---

src/sig_stfl/xmss/external/xmss_core_fast.c

Simple type fix. Enforce `idx` to `uint32_t` type to match the tree height.

Enforce idx from unsigned int to uint32_t.

---

docs/algorithms/kem/kyber.md
docs/algorithms/kem/kyber.yml
scripts/copy_from_upstream/copy_from_upstream.yml
src/kem/kyber/pqcrystals-kyber_kyber1024_avx2/verify.c
src/kem/kyber/pqcrystals-kyber_kyber1024_ref/poly.c
src/kem/kyber/pqcrystals-kyber_kyber1024_ref/verify.c
src/kem/kyber/pqcrystals-kyber_kyber512_avx2/verify.c
src/kem/kyber/pqcrystals-kyber_kyber512_ref/poly.c
src/kem/kyber/pqcrystals-kyber_kyber512_ref/verify.c
src/kem/kyber/pqcrystals-kyber_kyber768_avx2/verify.c
src/kem/kyber/pqcrystals-kyber_kyber768_ref/poly.c
src/kem/kyber/pqcrystals-kyber_kyber768_ref/verify.c

Pull latest Kyber version from upstream, which fixes a potential constant-time issue in the "ref" version as reported here:
https://groups.google.com/a/list.nist.gov/d/msgid/pqc-forum/ZXxUpck1501jEcRq%40localhost

Pull latest Kyber version from upstream

---

PLATFORMS.md

Implements results of [discussion on platforms supported](https://github.com/orgs/open-quantum-safe/discussions/1583).
* [no] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in fully supported downstream projects dependent on these, i.e., [oqs-provider](https://github.com/open-quantum-safe/oqs-provider) and [OQS-OpenSSH](https://github.com/open-quantum-safe/openssh) will also need to be ready for review and merge by the time this is merged.)

platform support documentation [skip ci]

---

.travis.yml
docs/algorithms/kem/kyber.md
docs/algorithms/kem/kyber.yml
scripts/copy_from_upstream/copy_from_upstream.yml
src/kem/kyber/pqcrystals-kyber_kyber1024_avx2/verify.c
src/kem/kyber/pqcrystals-kyber_kyber1024_ref/poly.c
src/kem/kyber/pqcrystals-kyber_kyber1024_ref/verify.c
src/kem/kyber/pqcrystals-kyber_kyber512_avx2/verify.c
src/kem/kyber/pqcrystals-kyber_kyber512_ref/poly.c
src/kem/kyber/pqcrystals-kyber_kyber512_ref/verify.c
src/kem/kyber/pqcrystals-kyber_kyber768_avx2/verify.c
src/kem/kyber/pqcrystals-kyber_kyber768_ref/poly.c
src/kem/kyber/pqcrystals-kyber_kyber768_ref/verify.c

Applies fix from #1631 to dev branch for 0.9.1 release.
* [No] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in fully supported downstream projects dependent on these, i.e., [oqs-provider](https://github.com/open-quantum-safe/oqs-provider) and [OQS-OpenSSH](https://github.com/open-quantum-safe/openssh) will also need to be ready for review and merge by the time this is merged.)

pull kyber from upstream: dda29cc63af721981ee2c831cf00822e69be3220 (#1631)

---

.travis.yml
docs/algorithms/kem/kyber.md
docs/algorithms/kem/kyber.yml
scripts/copy_from_upstream/copy_from_upstream.yml
scripts/copy_from_upstream/patches/pqclean-kyber-armneon-variable-timing-fix.patch
src/kem/kyber/pqclean_kyber1024_aarch64/poly.c
src/kem/kyber/pqclean_kyber512_aarch64/poly.c
src/kem/kyber/pqclean_kyber768_aarch64/poly.c
src/kem/kyber/pqcrystals-kyber_kyber1024_avx2/verify.c
src/kem/kyber/pqcrystals-kyber_kyber1024_ref/poly.c
src/kem/kyber/pqcrystals-kyber_kyber1024_ref/verify.c
src/kem/kyber/pqcrystals-kyber_kyber512_avx2/verify.c
src/kem/kyber/pqcrystals-kyber_kyber512_ref/poly.c
src/kem/kyber/pqcrystals-kyber_kyber512_ref/verify.c
src/kem/kyber/pqcrystals-kyber_kyber768_avx2/verify.c
src/kem/kyber/pqcrystals-kyber_kyber768_ref/poly.c
src/kem/kyber/pqcrystals-kyber_kyber768_ref/verify.c

Same fix as in #1636, but targeting 0.9.1.

Apply patch to Kyber aarch64 code from PQClean for variable-time division issue -> targeting 0.9.1

---

scripts/copy_from_upstream/copy_from_upstream.yml
scripts/copy_from_upstream/patches/pqclean-kyber-armneon-variable-timing-fix.patch
src/kem/kyber/oldpqclean_kyber1024_aarch64/poly.c
src/kem/kyber/oldpqclean_kyber512_aarch64/poly.c
src/kem/kyber/oldpqclean_kyber768_aarch64/poly.c

This is a follow-up to PR #1631.
Adds patch to aarch64 Kyber pulled from PQClean for issue with variable-time division in poly_tomsg.

Apply patch to Kyber aarch64 code from PQClean for variable-time division issue.

---

tests/constant_time/sig/passes/falcon_keygen

This PR fix Falcon constant time check in Valgrind. 
I review the Valgrind output and Falcon inline comments. It appears that a new line has been introduced, rendering the constant time check invalid. Consequently, adjusting the line location by 1 resolves the issue. To enhance clarity, I have separated the checks for Generic and AVX2. Additionally, I have eliminated some redundant checks for a more streamlined code.
Fixes #1617.

Fix falcon constant time check in Valgrind

---

CMakeLists.txt

Provides explanation for #1642 and documents minimal `cmake` version for objects list in generator expression. Also explains the need for https://github.com/open-quantum-safe/ci-containers/pull/68.
* [no] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in fully supported downstream projects dependent on these, i.e., [oqs-provider](https://github.com/open-quantum-safe/oqs-provider) and [OQS-OpenSSH](https://github.com/open-quantum-safe/openssh) will also need to be ready for review and merge by …

Correct cmake version requirement

---

docs/algorithms/kem/kyber.md
docs/algorithms/kem/kyber.yml
scripts/copy_from_upstream/copy_from_upstream.yml
scripts/copy_from_upstream/patches/pqclean-kyber-armneon-variable-timing-fix.patch
src/kem/kyber/oldpqclean_kyber1024_aarch64/poly.c
src/kem/kyber/oldpqclean_kyber1024_aarch64/polyvec.c
src/kem/kyber/oldpqclean_kyber512_aarch64/poly.c
src/kem/kyber/oldpqclean_kyber512_aarch64/polyvec.c
src/kem/kyber/oldpqclean_kyber768_aarch64/poly.c
src/kem/kyber/oldpqclean_kyber768_aarch64/polyvec.c
src/kem/kyber/pqcrystals-kyber_kyber1024_ref/poly.c
src/kem/kyber/pqcrystals-kyber_kyber1024_ref/polyvec.c
src/kem/kyber/pqcrystals-kyber_kyber512_ref/poly.c
src/kem/kyber/pqcrystals-kyber_kyber512_ref/polyvec.c
src/kem/kyber/pqcrystals-kyber_kyber768_ref/poly.c
src/kem/kyber/pqcrystals-kyber_kyber768_ref/polyvec.c

Pull recent fixes made to Kyber from [PQ-Crystals](https://github.com/pq-crystals/kyber/commit/272125f6acc8e8b6850fd68ceb901a660ff48196) into main branch and patches Kyber aarch64 implementation.
Fixes #1645 (see also #1652).
* [No] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in fully supported downstream projects dependent on these, i.e., [oqs-provider](https://github.com/open-quantum-safe/oqs-provider) and [OQS-OpenSSH](https://github.com/open-quantum-safe/openssh) will also need to be …

Pull Kyber division fixes from PQ-Crystals into main

---

.github/workflows/linux.yml
docs/algorithms/kem/classic_mceliece.md
docs/algorithms/kem/classic_mceliece.yml
docs/algorithms/kem/kyber.md
docs/algorithms/kem/kyber.yml
docs/algorithms/sig/falcon.md
scripts/copy_from_upstream/copy_from_upstream.py
scripts/copy_from_upstream/copy_from_upstream.yml
scripts/copy_from_upstream/patches/pqclean-kyber-armneon-variable-timing-fix.patch
src/kem/kyber/pqclean_kyber1024_aarch64/poly.c
src/kem/kyber/pqclean_kyber1024_aarch64/polyvec.c
src/kem/kyber/pqclean_kyber512_aarch64/poly.c
src/kem/kyber/pqclean_kyber512_aarch64/polyvec.c
src/kem/kyber/pqclean_kyber768_aarch64/poly.c
src/kem/kyber/pqclean_kyber768_aarch64/polyvec.c
src/kem/kyber/pqcrystals-kyber_kyber1024_ref/poly.c
src/kem/kyber/pqcrystals-kyber_kyber1024_ref/polyvec.c
src/kem/kyber/pqcrystals-kyber_kyber512_ref/poly.c
src/kem/kyber/pqcrystals-kyber_kyber512_ref/polyvec.c
src/kem/kyber/pqcrystals-kyber_kyber768_ref/poly.c
src/kem/kyber/pqcrystals-kyber_kyber768_ref/polyvec.c

Pull recent fixes made to Kyber from [PQ-Crystals](https://github.com/pq-crystals/kyber/commit/272125f6acc8e8b6850fd68ceb901a660ff48196) into dev-092 branch.
TODO: 
Fixes #1645 (see also #1649).
* [No] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in fully supported downstream projects dependent on these, i.e., [oqs-provider](https://github.com/open-quantum-safe/oqs-provider) and [OQS-OpenSSH](https://github.com/open-quantum-safe/openssh) will also need to be ready for review and merge by the …

Pull Kyber division fixes from PQ-Crystals into dev-092

---

CONFIGURE.md
src/common/common.c
src/common/common.h
src/common/sha2/sha2_armv8.c
src/common/sha2/sha2_c.c
src/common/sha3/ossl_sha3.c
src/common/sha3/ossl_sha3x4.c
src/common/sha3/xkcp_sha3.c
src/common/sha3/xkcp_sha3x4.c

As mentioned in #1650 , liboqs has a existing pattern `exit(111)` when the malloc allocation failed. This PR add `OQS_MEM_checked_malloc` and `OQS_MEM_checked_aligned_alloc`. 
Two APIs will abruptly exit the program, but *at least* let user know what happens. 
For now, it's close to impossible to propagate errors to callers without a lot of rewrite in the library.
There is a pattern in `sha2_armv8.c` and `sha2_c.c` that use the for loop to perform an array copy. 
Changed to `memcpy`. This change enables compiler optimizations. 
Fixed minor grammar errors, and add stateful signature flags description.
* [] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to …

Address  stateful-sigs comments in #1650

---

PLATFORMS.md
zephyr/CMakeLists.txt

This commit fixes platform support for Zephyr. Mainly, `x86_64` has been missing. Furthermore, the 32/64 bit handling has been improved and simplified. 
Zephyr support is now also properly documented in `PLATFORMS.md`.

Zephyr: fixes for platform support

---

zephyr/CMakeLists.txt

* Minor fixes for the `CMakeLists.txt` file in the `zephyr` directory propably happened during rebasing of #1641.
* Minor improvements to the Zephyr specific CMake workarounds
* RiscV distinct board references have been removed to support all RiscV boards Zephyr supports.

Zephyr: CMake fixes

---

LICENSE.txt

Update copyright year and note that the copyright is held by the authors of the contributions and not the project itself.

Clarify that copyright is held by authors and not the project itself [skip ci]

---

GOVERNANCE.md

Provide an initial framework for roles and voting processes. Combines elements of [oqs-provider/GOVERNANCE.md](https://github.com/open-quantum-safe/oqs-provider/blob/main/GOVERNANCE.md) with ideas from the [Falco Project governance document](https://github.com/falcosecurity/evolution/blob/main/GOVERNANCE.md).

Add a document describing our subproject governance

---

.CMake/alg_support.cmake
docs/algorithms/kem/bike.md
docs/algorithms/kem/bike.yml

We don't enable BIKE in x86 builds, and [enabling it on x86 leads to CI failures](https://app.circleci.com/pipelines/github/open-quantum-safe/liboqs/3279/workflows/e8d367d9-2717-4105-a2f4-4bee216b0de3/jobs/26246). This PR is to bring documentation in line with the build configuration.
Fixes #1443.
Notably, the [upstream implementation](https://github.com/awslabs/bike-kem/tree/master) does apparently support x86, so this is something we may wish to look into.
No to both.

Update BIKE documentation to exclude x86

---

GOVERNANCE.md

This PR fixed a typo in the link to the license file in `GOVERNANCE.md`

Fix link in GOVERNANCE.md

---

.github/workflows/weekly.yml

As expected, Falcon-1024 fails the weekly extended KAT tests. This will be the case until #1561 is resolved. For now, the failure creates unnecessary noise. This PR
1. renames the weekly test workflow to reflect that it's no longer just a constant-time test run and
2. skips the Falcon-1024 extended KAT tests.

Rename weekly runs and skip Falcon-1024 [skip ci]

---

.github/workflows/weekly.yml
tests/constant_time/kem/issues/classic-mceliece-348864
tests/constant_time/kem/issues/classic-mceliece-348864f
tests/constant_time/kem/issues/classic-mceliece-460896
tests/constant_time/kem/issues/classic-mceliece-460896f
tests/constant_time/kem/issues/classic-mceliece-6688128
tests/constant_time/kem/issues/classic-mceliece-6688128f
tests/constant_time/kem/issues/classic-mceliece-6960119
tests/constant_time/kem/issues/classic-mceliece-6960119f
tests/constant_time/kem/issues/classic-mceliece-8192128
tests/constant_time/kem/issues/classic-mceliece-8192128f

This PR updates the suppression files for the "clean" (pure C) implementation of Classic McEliece. I've run the tests both in a container built from the CI image and locally on my machine.
For now, I've labelled all of these as "issues", as I'm not knowledgeable enough about McEliece to confidently classify them as false positives or true instances of secret-dependent behaviour. I believe that this is in line with what we had done previously for the AVX2 constant-time failures.
To test:
```bash
rm -rf build && mkdir build && cd build
cmake -GNinja -DOQS_DIST_BUILD=OFF -DOQS_OPT_TARGET=generic -DCMAKE_BUILD_TYPE=Debug -DOQS_ENABLE_TEST_CONSTANT_TIME=ON .. && ninja ; cd -
python3 -m pytest -n=auto -k "McEliece" -v tests/test_constant_time.py
```
Partially addresses #1666.
I suspect that …

Update McEliece suppression files for generic config

---

SECURITY.md

Update security status of library releases. [Release wiki](https://github.com/open-quantum-safe/liboqs/wiki/Release-process#code-change) has been amended to avoid such omissions from happening again.
* [no] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in fully supported downstream projects dependent on these, i.e., [oqs-provider](https://github.com/open-quantum-safe/oqs-provider) and [OQS-OpenSSH](https://github.com/open-quantum-safe/openssh) will also need to be ready for review and merge by …

properly document release support level [skip ci]

---

.CMake/compiler_opts.cmake

Fixes #1693.
Looks like if cross-compiling from POSIX to Windows, the CMake detect pthreads as available on the host and sets OQS_USE_PTHREADS ON for compilation, which will not work on windows.

set(OQS_USE_PTHREADS OFF) on MinGW/Cygwin

---

.github/workflows/android.yml
.github/workflows/apple.yml
.github/workflows/linux.yml
.github/workflows/windows.yml
scripts/build-android.sh
tests/kat_sig_stfl.c

Integrate stateful signatures into our CI workflows.
I took the approach of simply switching on LMS and XMSS for all of our GitHub Actions builds that support all algorithms and adding an additional run in select places to test the configuration in which keygen and sign are disabled.
It looks like the logic around enabling / disabling keygen/sign needs to be tweaked in the XMSS KAT testing function.
We still need to test these on MacOS, which will require updating CircleCI, but I thought it best to put this draft up here as is for now to unblock anyone who wants to work on the test failures.

Update GitHub Actions workflows for stateful signatures

---

README.md

update brew install instructions to use openssl@3 instead of openssl@1.1.1 [skip ci]

update brew install instructions to use openssl@3 instead of openssl@1.1.1 [skip ci]

---

README.md

Update liboqs readme to point to oqs-provider instead of deprecated openssl1.1.1 fork [skip ci]
This PR updates the OpenSSL link to point to oqs-provider now that OpenSSL1.1.1 is deprecated.

Update liboqs readme to point to oqs-provider instead of deprecated openssl1.1.1 fork [skip ci]

---

src/sig_stfl/xmss/sig_stfl_xmss.h
src/sig_stfl/xmss/sig_stfl_xmss_secret_key_functions.c

Add return status for XMSS lock/unlock functions.

---

.github/pull_request_template.md
CONFIGURE.md

This removes no longer warranted references to oqs-openssh.
* [no] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in fully supported downstream projects dependent on these, i.e., [oqs-provider](https://github.com/open-quantum-safe/oqs-provider) and [OQS-OpenSSH](https://github.com/open-quantum-safe/openssh) will also need to be ready for review and merge by the time this is merged.)

remove references to unsupported openssh [skip ci]

---

.github/workflows/unix.yml
README.md

fix documentation generation

---

src/sig_stfl/xmss/sig_stfl_xmss_functions.c
src/sig_stfl/xmss/sig_stfl_xmssmt_functions.c

Fix missing lock/unlock check in XMSS.

Add return check for lock/unlock function

---

src/common/common.c

I find that if we use `exit()`, we don't know where it goes wrong. 
So if we switch to `abort()`, we will have the trace where it crashed. 
```
abort() causes abnormal program termination and does not call functions registered with atexit() or destructors for objects with automatic storage duration.[[1]](https://en.cppreference.com/w/c/program/abort) It is generally used to immediately terminate the program when a fatal error occurs.
```
also, `abort()` will cause a signal, and it's up to application to decide what to do with the signal.

Use `abort()` instead of `exit()` to get the trace log.

---

src/CMakeLists.txt
tests/CMakeLists.txt

Since `liboqs-internal` (see #1667) is never actually installed on the user's system, it doesn't make sense to build it as a shared library and then link the test programs against it. This PR forces `liboqs-internal` to be built as a static library regardless of the `BUILD_SHARED_LIBS` variable.
Fixes #1723.

Always build "internal" library as static

---

scripts/copy_from_xkcp/patches/lib_low_KeccakP-1600_AVX2_KeccakP-1600-AVX2.s
src/common/sha3/xkcp_low/KeccakP-1600/avx2/KeccakP-1600-AVX2.S

rhotates tables are placed to .text section which confuses tools such as
BOLT. Move them to rodata to unbreak and avoid polluting icache/iTLB
with data.
1. Update patch file using the steps in scripts/copy_from_xkcp/README
2. Apply the updated patch with scripts/copy_from_xkcp/package.sh
Sync with XKCP upstream: https://github.com/XKCP/XKCP/pull/137 
Similar fix in OpenSSL: https://github.com/openssl/openssl/pull/21440 
Redo of https://github.com/open-quantum-safe/liboqs/pull/1508
Signed-off-by: Amir Ayupov <aaupov@fb.com>

[NFCI] Move Keccak rhotates tables to rodata

---

.gitignore

We set CMAKE_EXPORT_COMPILE_COMMANDS=ON so the compilation database is automatically exported to the build directory. However, many language servers expect this file to be in the project root directory, so a common post-build step is to:
```shell
$ ln -s <build-directory>/compile_commands.json
```
This PR enables developers to do this without having to worry about accidentally commiting a symlink file.

add compile_commands.json to .gitignore

---

PLATFORMS.md

oqs-provider has been testing `cygwin` support also for `liboqs`. But this now fails for two reasons:
- OpenSSL 3.4 triggers a crash
- Activating the `pytest` toolchain in `cygwin` is [not seamlessly possible](https://github.com/open-quantum-safe/oqs-provider/pull/401/commits/aeb3ad296a70389711f267032c7be6b60ba8252b).
This PR therefore restricts stated Windows support to MSVC until a formal decision is taken to enhance Windows support beyond this (& adding CI in this project).
* [no] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR …

restrict Windows platform support documentation [skip ci]

---

.circleci/config.yml
.travis.yml

Activate stateful hash-based signatures in the CI builds for ARM64, PowerPC, and s390x.

Test stateful sigs on arm64, s390x, and powerpc

---

CONFIGURE.md

Algorithm selection clarification

---

src/common/rand/rand_nist.c

The handleErrors function should print out errors when OPENSSL_NO_STDIO is set. The ERR_clear_error function is called instead since ERR_print_errors_fp would empty the error queue.

Errors not printed out when OPENSSL_NO_STDIO is set

---

.github/workflows/unix.yml

Attempts to verify cause of recent build failures by patching the gcc compiler for macOS 13.3.0 -> 13.2.0
See issue #1804

Force gcc 13.2.0 over 13.3.0

---

src/sig_stfl/sig_stfl.h

When an application (e.g., `oqs-provider`) includes `<oqs/sig.h>`, the following happens:
- `sig.h` includes `oqs.h` _at the top of the file_.
- `oqs.h` includes `sig.h`, but this include is skipped because of the `OQS_SIG_H` include guard.
- `oqs.h` includes `sig_stfl.h`.
- `sig_stfl.h` references `OQS_SIG`, which has not yet been defined.
This breaks the application's build: see https://github.com/open-quantum-safe/liboqs/issues/1815, https://github.com/open-quantum-safe/oqs-provider/issues/427, and https://github.com/open-quantum-safe/oqs-demos/issues/281.
This PR resolves the issue by forward-declaring the OQS_SIG type in `sig_stfl.h`. This fixes the failing `oqs-provider` build: see the downstream tests [before](https://github.com/open-quantum-safe/oqs-provider/actions/runs/9468608791 …

Forward-declare OQS_SIG in sig_stfl.h

---

.circleci/config.yml
.github/workflows/unix.yml

This PR moves the CircleCI ARM64 Linux "build" test over to GitHub Actions, using the new oqs-arm64 runner.
It also fixes some GitHub syntax so that jobs are skipped when we expect them to be.
Makes progress on #1795.

Move Linux ARM64 "build" test from CircleCI to GitHub Actions

---

tests/test_alg_info.py

Fix test_alg_info.py on Windows which cause the ninja run_tests failure.
Since `gerp` is not available on Windows, making use of powershell is a good alternative way to replace grep.

Fix test_alg_info.py on Windows platform

---

CMakeLists.txt
docs/.Doxyfile
src/common/aes/aes.h
src/common/aes/aes_ops.h
src/common/sha2/sha2.h
src/common/sha2/sha2_ops.h
src/common/sha3/sha3.h
src/common/sha3/sha3_ops.h
src/common/sha3/sha3x4.h
src/common/sha3/sha3x4_ops.h
src/oqs.h

This makes the callback API to replace low-level cryptographic implementation public again after open-quantum-safe#1667.
The purpose of this PR is to replace the implementation of symmetric primitives such as SHA3 used in ML-KEM, through the public API. That was my intention in #1603 but I didn't realize that `<oqs/aes.h>` and co. are moved to internal-only and no longer installed. This patch would make the GnuTLS liboqs [integration](https://gitlab.com/gnutls/gnutls/-/merge_requests/1842) self-contained.

Expose callback API for replacing low-level cryptographic primitives

---

README.md

This PR updates and fixes the CI status badges in the README.
Changes made:
1. Removed redundant text labels preceding the badges.
2. Corrected the broken Travis CI badge and URL and switched to shields.io for the badge to include the logo.
3. Updated the CircleCI badge to use the shield style for visual consistency with the other badge.
Note: This is a purely cosmetic change to the markdown file. It does not add new features, affect input/output behavior, or alter the list of algorithms. No version bump or downstream project updates are required.

Update and fix CI status badges

---

.circleci/config.yml
.github/workflows/unix.yml
.github/workflows/weekly.yml
.travis.yml
README.md

To ensure that printing config variables doesn't have undesired side effects.
Mitigates #1847.

Use `cmake -LA -N` instead of `cmake -LA` in CI

---

CONTRIBUTING.md
scripts/format_code.sh
tests/run_astyle.sh

The behaviour of `astyle` varies across versions and platforms, which means it can sometimes be a pain to get PRs to pass CI formatting checks. This PR adds a convenience script which runs `astyle` over local code in the CI Docker image, ensuring that local formatting matches what's expected by CI.
My hope is that this script will reduce friction for new contributors and busywork for regular ones. I've been using this approach for a while myself.

Add a convenience script for consistent astyle formatting

---

tests/kat_sig_stfl.c

Gets rid of some annoying compiler warnings.
Fixes #1871.

Check return value of fscanf in LMS/XMSS KAT tests

---

.github/workflows/commit-to-main.yml

Corrects my incorrect use of GitHub environment variables in https://github.com/open-quantum-safe/liboqs/pull/1849, making the downstream trigger pass.
I had previously tested the scripts locally but not in CI. The workflow for this PR is CI-tested here: https://github.com/open-quantum-safe/liboqs/actions/runs/10083919855

Fix downstream CI trigger

---

tests/example_sig_stfl.c

Fixes #1886. Thanks @wangweij for the report!

Fix overflow in stateful sigs tests

---

.github/workflows/commit-to-main.yml

As per https://github.com/open-quantum-safe/openssh/issues/166.
~* [ ] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)~
~* [ ] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in fully supported downstream projects dependent on these, i.e., [oqs-provider](https://github.com/open-quantum-safe/oqs-provider) will also need to be ready for review and merge by the time this is merged.)~

Update OpenSSH downstream branch to OQS-v9

---

.github/workflows/unix.yml
.github/workflows/weekly.yml

An incorrect merge with main in #1745 broke the formatting in `.github/workflows/unix.yml` which was not caught before the PR was merged causing some CI workflows to not run; this fixes that.  
[No] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
[No] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in fully supported downstream projects dependent on these, i.e., [oqs-provider](https://github.com/open-quantum-safe/oqs-provider) will also need to be ready for review and merge by the time this is merged.)

Fix incorrect formatting in unix.yml

---

.github/workflows/weekly.yml

This updates the checkout action in used in `.github/workflows/weekly.yml` from v2 to v4. 
Weekly tests fail currently due to an unexpected formatting error which persists on re-running the failed jobs (see https://github.com/open-quantum-safe/liboqs/actions/runs/10542663074). The variable expansion for `matrix.CMAKE_ARGS` occurring on line 76 of weekly.yml seems to strip surrounding whitespace:
`run: mkdir build && cd build && cmake -GNinja ${{ matrix.CMAKE_ARGS }} .. && cmake -LA -N ..` 
The tests run correctly with checkout v4 (see https://github.com/open-quantum-safe/liboqs/actions/runs/10582643980).
Fixes #1906. 
[No] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required …

Update checkout action in weekly.yml

---

.github/actionlint.yaml
.github/workflows/basic.yml
CONTRIBUTING.md

This PR adds an Actionlint workflow to validate GH actions as per #1866
This is an updated version of PR #1880, taking into account the discussion on that contribution.
Actionlint checking would have protected against the changes fixed in #1869 and #1902, e.g. (for the latter):
```
➜ actionlint .github/workflows/*.yml
.github/workflows/linux.yml:176:5: unexpected key "libjade-build" for "job" section. expected one of "concurrency", "container", "continue-on-error", "defaults", "env", "environment", "if", "name", "needs", "outputs", "permissions", "runs-on", "secrets", "services", "steps", "strategy", "timeout-minutes", "uses", "with" [syntax-check]
|
176 |     libjade-build:
|     ^~~~~~~~~~~~~~
.github/workflows/linux.yml:187:84: property "libjade-build" is not defined in object type …
```

Check workflows for issues during CI

---

scripts/copy_from_upstream/copy_from_upstream.yml
scripts/copy_from_upstream/patches/pqclean-kyber-armneon-asan.patch
src/kem/kyber/oldpqclean_kyber1024_aarch64/neon_symmetric-shake.c
src/kem/kyber/oldpqclean_kyber512_aarch64/neon_symmetric-shake.c
src/kem/kyber/oldpqclean_kyber768_aarch64/neon_symmetric-shake.c

Patch Kyber to fix address sanitiser issue on ARM64 as described in #1914. Patch copied from [PQClean](https://github.com/PQClean/PQClean/blob/0c5bb143456333cd6ac85435d344b08b351b27a8/crypto_kem/kyber512/aarch64/neon_symmetric-shake.c#L59-L60), in line with fix submitted in #1914. 
* [No] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in fully supported downstream projects dependent on these, i.e., [oqs-provider](https://github.com/open-quantum-safe/oqs-provider) will also need to be ready for …

Patch Kyber to fix ASAN error on ARM64

---

README.md

Fixes #1897.
* [No] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in fully supported downstream projects dependent on these, i.e., [oqs-provider](https://github.com/open-quantum-safe/oqs-provider) will also need to be ready for review and merge by the time this is merged.)

Change README links to be doxygen-friendly

---

tests/test_acvp_vectors.py

If a user has passed a custom build path to cmake, and then calls for example `ninja -C <custom_build_path> run_tests`, the script test_acvp_vectors.py fails due to having "build" harcoded in the calls.
Instead, let's use `helpers.get_current_build_dir_name()` to get the build path and use that instead. This is already done in other scripts (e.g., test_binary.py)
Fixes #1937

Remove hardcoded build patch from test script

---

src/common/ossl_helpers.c

dlfcn.h is a Posix library not natively available on Windows. Only include the header for non-Windows builds. 
Fixes #1935

Don't include dlfcn.h for Windows

---

docs/cbom.json
scripts/update_cbom.py
scripts/validate_cbom.sh

Updates the CBOM generated to the format from the official CycloneDX 1.6 release:
https://cyclonedx.org/docs/1.6/json/
Closes #1831 #1753

Update CBOM format to upstream v1.6

---

.github/workflows/zephyr.yml

Downgrade zephyr container to v0.26.14 to avoid build failures

---

.github/workflows/basic.yml
CMakeLists.txt
CONFIGURE.md
docs/FUZZING.md
tests/CMakeLists.txt
tests/fuzz_test_dilithium2.c

The purpose of this PR is to improve the overall security of liboqs. This is by adding a very basic fuzz as described here https://github.com/open-quantum-safe/liboqs/issues/1215.
This PR just adds a new style of test i.e. a fuzz test and therefore doesn't need additional unit tests. Integrating this into the CI isn't currently possible but I've got a bit of a plan as to how to go ahead with it which I've described [here](https://github.com/open-quantum-safe/liboqs/issues/1215).

Add a basic fuzz testing harness for Dilithium2

---

README.md
scripts/noregress.sh
tests/CMakeLists.txt
tests/ds_benchmark.h
tests/speed_sig_stfl.c
tests/test_speed.py

This pull requests adds an executable `tests/speed_sig_stfl` to be able to benchmark the stateful hash based schemes in liboqs.
The source code `tests/speed_sig_stfl.c` is directly copied from `tests/speed_sig.c`,
but making the relevant changes to use the SIG_STFL functions and types instead.
Here are some issues encountered specific to SIG_STFL code:
- A secure store needs to be set for the secret key, the context must not be NULL
- A stfl sig has a maximum number of signatures, potentially as low as 2^5=32. One needs to create a new secret key once this number of signatures has been reached.
- key generation and signing can be extremely costly for some stfl sig algorithms. Automatic testing should focus only on small parameters.
- You cannot create a new secret key over an old (used …

Add benchmarking for stateful hash based schemes: speed_sig_stfl

---

.github/workflows/basic.yml
docs/FUZZING.md
tests/CMakeLists.txt
tests/fuzz_test_sig.c

Adapts existing fuzz-harness to support more algorithms.
This is a continuation of the effort described in #1215

Adapt existing sig fuzz harness including more algorithms

---

.github/workflows/basic.yml
cpp/sig_linking_test.cpp

Already worked on this code before - just added the variable to compile with Dilithium-2 support. It's already run in my local version of the repo.
It should be good to merge - but maybe one more glance over would be ideal.

add C++ linking test

---

tests/fuzz_test_sig.c

Make random/functions deterministic during fuzzing

---

.github/workflows/macos.yml

See https://github.com/actions/runner-images/issues/10721.
Fixes #1976.

Remove macos-12 runner due to GitHub deprecation.

---

src/common/ossl_helpers.c

When OQS_DLOPEN_OPENSSL is designated and low-level primitives are overridden with OQS_*_set_callbacks, OQS_destroy still indirectly calls EVP_*_free from OpenSSL. This adds a extra NULL check to avoid that.

Avoid OpenSSL functions are unconditionally called at OQS_destroy

---

src/sig_stfl/lms/external/hss_alloc.c
src/sig_stfl/lms/external/hss_sign.c

HSS signing operation crashed after exhausting the number of signatures available at a given level.
The multi-level tree was not properly populated.
Fixes #1966.

Fix LMS crash

---

scripts/copy_from_upstream/patches/pqcrystals-ml_kem.patch
src/kem/ml_kem/kem_ml_kem_1024.c
src/kem/ml_kem/kem_ml_kem_512.c
src/kem/ml_kem/kem_ml_kem_768.c

To bring ML-KEM in line with the upcoming ML-DSA update.
Fixes #1996

Set ML-KEM alg_version to "FIPS203"

---

tests/test_sig.c
tests/vectors_sig.c

This PR does the following:
1. add checks for malloc() failures
2. harden checks for random number length
3. add log messages in case of failure
Also, tried enabling ML-DSA ACVP tests on Windows but run into "character too long" on DSA-87

Minor changes to ML_DSA ACVP tests

---

.github/workflows/linux.yml

I received an email from Github that they will be disabling workflow jobs that use version 3 of actions/upload-artifact or actions/download-artifact in early 2025.  We are using v3 in one spot.  This PR updates the dependency to version 4.

Update upload-artifact action to v4

---

.github/workflows/basic.yml
tests/test_acvp_vectors.py

This fixes #2018 using `helpers.get_current_build_dir_name()`
In addition, [the basic workflow](https://github.com/open-quantum-safe/liboqs/blob/main/.github/workflows/basic.yml) is modified to use a random build path. Hopefully, this small change will catch future changes that introduce hardcoded paths.

Remove hardcoded build paths & modify basic workflow to build in random path

---

.github/workflows/linux.yml
.github/workflows/scorecard.yml

- Updates to use scorecard v5
- re-pinned actions in scorecard.yaml to latest levels
- fixed report of unpinned dependencies in unix.yml
- enabled publishing of scorecard results
Note: Results are published by the openssf team at https://scorecard.dev/viewer/?uri=github.com%2Fopen-quantum-safe%2Fliboqs
Enabling our own scan is recommended by openssf, allows us to enable badges, and permits some tweaking of rules
The current scan results are [here](https://scorecard.dev/viewer/?uri=github.com%2Fopen-quantum-safe%2Fliboqs)
Fixes #1830 
n/a
No change to crypto. This is build pipeline only.

#1830 update scorecard to v5 (gh action 2.4.0)

---

.github/actionlint.yaml
.github/workflows/linux.yml

The GitHub ARM runners are now available to the general public.
Related: https://github.com/open-quantum-safe/oqs-demos/issues/332.

Update to public Ubuntu 24.04 ARM runner

---

.github/workflows/linux.yml

As a follow-up of commit 64bceb37fafa9b90cf228965079de9ebd77a83b9, this checks that the library artifacts don't contain any unresolved symbols from libcrypto.so when it is dynamically loaded.

CI: Check unresolved symbols when compiled with OQS_DLOPEN_OPENSSL

---

tests/example_kem.c
tests/example_sig.c
tests/test_cmdline.py

This PR
- updates example_kem and example_sig to use ML-KEM and ML-DSA instead of Kyber and Dilithium
- adds example_sig_stfl to test_cmdline.py.

Update example files

---

.github/actionlint.yaml
.github/workflows/macos.yml
.github/workflows/windows.yml
PLATFORMS.md

This PR does the following:
- Adds the new (beta) GitHub runners for Windows 2025 and macOS 15.
- Updates PLATFORMS.md accordingly.
- Sets macOS runners to use gcc-14 (now supported by all runners) instead of gcc-13.
- Removes the GCC 13 patching logic from CI.
Closes #1804.

GitHub runner updates

---

.github/workflows/linux.yml

Temoporarily disable cupqc-buildcheck in linux.yml until the CI failure is resolved.

Disable cupqc-buildcheck

---

src/CMakeLists.txt

liboqsTargets.cmake is supposed to be adjacent liboqsConfig.cmake for the
latter to be functional.  This change ensure that this condition is met in
the build directory, allowing other CMake projects to build against a liboqs
build directory (as should be possible, implied by the use of 'export()').

Ensure that building against liboqs build directory works

---

.github/workflows/linux.yml

Github recently turned off their old caching APIs: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down.
liboqs' CI started failing with the following error message for me: This request has been automatically failed because it uses a deprecated version of `actions/cache: e12d46a63a90f2fae62d114769bbf2a179198b5c`. Please update your workflow to use v3/v4 of actions/cache to avoid interruptions.
This commit updates to the newer version of actions/cache that is using the new Github APIs.
Note that Github's blog post is misleading. A lot more versions than v1/v2 are being disabled including v3.3.3 that is used in liboqs - see …

Update actions/cache to v4.2.2

---

PLATFORMS.md
README.md
SECURITY.md
docs/.Doxyfile
scripts/run_doxygen.sh

- Adds references to the future OQS security response process document in README.md and SECURITY.md.
- Updates SECURITY.md to discourage releases below 0.12.0 due to the HQC vulnerability.
Not to be merged until https://github.com/open-quantum-safe/tsc/pull/124 lands.

Add references to security response process

---

docs/algorithms/sig/mayo.yml
docs/algorithms/sig/uov.yml

Fix in UOV and MAYO data sheet: nist-round should be 2

Update nist-round in UOV and MAYO data sheet

---

.CMake/alg_support.cmake
scripts/copy_from_upstream/.CMake/alg_support.cmake/add_enable_by_alg.fragment
scripts/copy_from_upstream/copy_from_upstream.yml

Recently a [security flaw in the IND-CCA2 security of HQC](https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/Wiu4ZQo3fP8) was announced. A fix from the HQC is forthcoming.  This PR proposes disabling HQC from the default build for the liboqs 0.13.0 release.
Note that copy_from_upstream consistency checks will fail since I have manually overridden a CMakeLists variable to disable the algorithm.
The following text can be included in the liboqs 0.13.0 release notes:
> - HQC: Due to a [recently announced security flaw in the IND-CCA2 security of HQC](https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/Wiu4ZQo3fP8), the HQC code in liboqs has been disabled by default. It will be re-enabled in a future release when a revised version of HQC is available.
* [No] Does this PR change the …

Temporarily disable HQC

---

.github/workflows/commit-to-main.yml
.github/workflows/pr.yml
.github/workflows/scorecard.yml
.github/workflows/weekly.yml

PR workflow runs (specifically, the OpenSSF scorecard runs) are failing at startup due to an issue with the GitHub Actions configuration. It looks like GitHub has added a new `models` option that needs to be given a value.

Fix PR workflow runs

---

.CMake/compiler_opts.cmake

This PR:
1. Restricts `-Wno-maybe-uninitialized` to GCC, fixing Clang warnings on Windows (e.g., MSYS2).
2. Fixes stack size typo from `1677216` to `16777216` (16MB) for consistency.
Fixes #2108
- Restricted `-Wno-maybe-uninitialized` to GCC with `CMAKE_C_COMPILER_ID STREQUAL "GNU"`.
- Corrected stack size in `CMAKE_EXE_LINKER_FLAGS` to `16777216`.

Restrict -Wno-maybe-uninitialized to GCC and fix stack size typo

---

GOVERNANCE.md

As per the April 1 TSC meeting, I've offered to step up as a maintainer for liboqs. Per GOVERNANCE.md, this appointment requires a majority approval from the current group of committers and can be vetoed by any maintainer.
When reading through the GOVERNANCE.md file, I saw a couple of opportunities for updates:
- Michael's leave of absence has now been documented.
- John Schanck has now been removed from the list of Committers as per https://github.com/open-quantum-safe/tsc/pull/126.
I've added a "Former Committers" section to the document to acknowledge John's contributions.
With that, I believe the list of voting committers is
- @bhess 
- @christianpaquin 
- @dstebila 
- @Martyrshot 
- @praveksharma 
- @SWilson4 
- @vsoftco 
Not sure if I count as a voting member here? :laughing: I will …

Promote @SWilson4 from Committer to Maintainer [skip ci]

---

docs/algorithms/kem/ml_kem.md
docs/algorithms/kem/ml_kem.yml
scripts/copy_from_upstream/copy_from_upstream.yml

Changes cuPQC upstream from a personal repo to an OQS one. Fixes #2053.

Change cuPQC upstream repo

---

src/sig/sig.c
src/sig/sig.h

Hi, this PR introduces a new API function:
```c
OQS_API bool OQS_SIG_supports_ctx_str(const char *alg_name);
``` 
- This allows for projects like liboqs-python to be able to check whether a given siguature algorithm supports context strings or not, without relying on internal structures.
<br>
This was done because I noticed liboqs-python's CI [kept failing](https://github.com/open-quantum-safe/liboqs-python/actions/runs/14085054590/job/39446808787), due to context string-related tests running on algorithms that don't support them, there was a work-around in the pytest but that became a bit convoluted (at least more than if liboqs itself had a feature like this).
<details><summary>I was able to have a C-side test to check API and struct consistency for all enabled signature algorithms, I …

Add a function to check if context string is supported

---

.github/workflows/macos.yml

One Github Actions workflow has been failing (macos-15, gcc-14), seemingly not related to a change we've made. This PR temporarily disables it.
See discussion in https://github.com/open-quantum-safe/liboqs/pull/2148

Skip failing CI test

---

.github/workflows/macos.yml
src/common/rand/rand_nist.c
src/sig_stfl/lms/external/hss_reserve.c
src/sig_stfl/lms/external/hss_sign.c
src/sig_stfl/lms/sig_stfl_lms.c
src/sig_stfl/lms/sig_stfl_lms_functions.c
src/sig_stfl/xmss/external/xmss_core_fast.c
src/sig_stfl/xmss/sig_stfl_xmss_secret_key_functions.c
tests/kat_sig_stfl.c
tests/test_kem.c
tests/test_sig_stfl.c

This is needed for secret objects as memset
maybe optimized out by the compiler.
Fixes https://github.com/open-quantum-safe/liboqs/issues/1864

Use OQS_MEM_cleanse() instead of memset()

---

tests/CMakeLists.txt
tests/fuzz_test_kem.c

Adds basic fuzz harness for kem algorithms
This is part of work towards: #1215

test: Add basic kem fuzz testing

---

dev/bench/index.html

This PR is a continuation of #2134, which aims to adjust some details of the generated html file so the layout shows as in https://pablo-gf.github.io/liboqs/dev/bench/ . I could not include these changes to the previous PR because the file was not yet generated.

Adjust HTML file for the continuous benchamarking page

---

.github/workflows/kem-bench.yml
.github/workflows/sig-bench.yml

Reduce the number of comments posted/emailed by benchmark regression testing.

Benchmarking comments only on alerts

---

.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/pr.yml
.github/workflows/windows.yml

Added custom timeout for `platform-tests` job of the `Pull request tests` workflow based on historical data that could lead to resource savings and faster CI for the project.
Over the last 20670 successful runs, the `platform-tests` job has a maximum runtime of 61 minutes (mean=7, std=8) across all matrix combinations that arise from the called actions.
However, there are failed runs that fail after reaching the threshold of 6 hours that GitHub imposes. In other words, these jobs seem to get stuck, possibly for external or random reasons. 
One such example is [this](https://github.com/open-quantum-safe/liboqs/actions/runs/13566979003/job/37922797116) job run, that failed after 6 hours. More stuck jobs have been observed over the last months, the first one on 17-Oct-2024 and the last one …

Added Custom Timeout to CI

---

.CMake/toolchain_armel.cmake
.github/workflows/linux.yml

Since armel is no longer a supported platform, the commented out workflow in `linux.yml` can be removed.

Remove armel comment

---

.github/workflows/weekly.yml

Per #2260, `.github/workflows/scorecard.yml` requests `content: read` permissions, but `.github/workflows/weekly.yml` did not explicitly give such permission, causing weekly tests to fail.

add content:read permission to scorecard workflow

---

CONTRIBUTING.md

Adds a link for the newly created [contribution wishlist](https://github.com/open-quantum-safe/liboqs/wiki/Contribution-wishlist) to the CONTRIBUTING.md document.

Link to contribution wishlist from CONTRIBUTING.md [skip ci]

---

tests/test_acvp_vectors.py

It appears that #2237 inadvertently disabled running all ACVP tests in test_acvp_vectors.py, which I missed during review.
This PR re-enables running all ACVP tests.

Re-enable all ACVP tests

---

tests/speed_sig.c

Fix an incorrect Actual signature length (0) in sig fullcycle speed test
Fix #2292

Fix incorrect Actual signature length (0) in sig fullcycle speed test
