- .gitignore
- README.md
- VisualStudio/liboqs.sln
- VisualStudio/oqs/oqs.vcxproj
- VisualStudio/oqs/oqs.vcxproj.filters
- VisualStudio/test_kex/test_kex.vcxproj
- VisualStudio/test_kex/test_kex.vcxproj.filters
- VisualStudio/test_rand/test_rand.vcxproj
- VisualStudio/test_rand/test_rand.vcxproj.filters
- src/kex_rlwe_bcns15/kex_rlwe_bcns15.c
- src/kex_rlwe_bcns15/rlwe.c
- src/rand/rand.c
- src/rand_urandom_chacha20/rand_urandom_chacha20.c
I added a Visual Studio solution to enable building on Windows. I replaced randlib's dev/random call with a CAPI call, and tweaked some code that created compilation issues on Windows.
> Enables Windows build.

- Makefile
- src/rand/rand.c
- src/rand/rand.h
- src/rand/test_rand.c
- src/rand_urandom_aesctr/rand_urandom_aesctr.c
- src/rand_urandom_aesctr/rand_urandom_aesctr.h
For now the nonce is chosen randomly.  I can add it as a parameter if it is needed? Issue #36.
> Add PRNG based on AES-CTR

- Makefile
- src/common/common.c
- src/common/common.h
Adds a function to zero memory as discussed in #48. Will add more add some more commits to this pull request using it in various places.
> Add function for zeroing memory.

- src/kex_lwe_frodo/lwe.c
- src/kex_rlwe_newhope/poly.c
Doing a scan-build of the source I discovered these two statements that appear to be unnecessary (since b is set to zero at the beginning of the loop).  I was wondering if they should have some affect and there is an implementation error or if they can be safely removed?
I also included some minor code cleanup where variable scope is reduced.
> Remove statements which have no affect.

- src/kex_sidh_cln16/SIDH_setup.c
- src/kex_sidh_cln16/kex_sidh_cln16.c
Just fixes a few possible memory leaks identified by scan-build.
Not sure if this needs much review so I will merge it soon if there are no comments.
> Fix possible memory leaks.

- src/kex_sidh_iqc_ref/sidh_elliptic_curve.c
- src/kex_sidh_iqc_ref/sidh_elliptic_curve.h
- src/kex_sidh_iqc_ref/sidh_elliptic_curve_dlp.c
- src/kex_sidh_iqc_ref/sidh_elliptic_curve_dlp.h
- src/kex_sidh_iqc_ref/sidh_isogeny.c
- src/kex_sidh_iqc_ref/sidh_isogeny.h
- src/kex_sidh_iqc_ref/sidh_private_key.c
- src/kex_sidh_iqc_ref/sidh_private_key.h
- src/kex_sidh_iqc_ref/sidh_public_key.c
- src/kex_sidh_iqc_ref/sidh_public_key.h
- src/kex_sidh_iqc_ref/sidh_public_key_encryption.c
- src/kex_sidh_iqc_ref/sidh_public_key_encryption.h
- src/kex_sidh_iqc_ref/sidh_public_key_validation.c
- src/kex_sidh_iqc_ref/sidh_public_key_validation.h
- src/kex_sidh_iqc_ref/sidh_public_param.c
- src/kex_sidh_iqc_ref/sidh_public_param.h
- src/kex_sidh_iqc_ref/sidh_quadratic_ext.c
- src/kex_sidh_iqc_ref/sidh_quadratic_ext.h
- src/kex_sidh_iqc_ref/sidh_shared_key.c
- src/kex_sidh_iqc_ref/sidh_shared_key.h
- src/kex_sidh_iqc_ref/sidh_util.c
- src/kex_sidh_iqc_ref/sidh_util.h
With permission of original author, Javad Doliskani
> Remove GPL headers to relicense kex_sidh_iqc_ref as MIT licensed

- README.md
> README: fixed rand.h link

- README.md
> Doc for Kyber

- Makefile.am
> Add --quiet flag during Travis tests.

- README.md
- appveyor.yml
Added support for Windows Continuous Integration with Appveyor, fixing Issue #149
> Windows continuous integration

- .travis.yml
- README.md
- VisualStudio/liboqs.sln
- VisualStudio/oqs/oqs.vcxproj
- VisualStudio/oqs/oqs.vcxproj.filters
- VisualStudio/test_kex/test_kex.vcxproj
- VisualStudio/test_rand/test_rand.vcxproj
- VisualStudio/test_sig/test_sig.vcxproj
- VisualStudio/test_sig/test_sig.vcxproj.filters
- src/crypto/rand/rand.c
- src/crypto/rand_urandom_aesctr/rand_urandom_aesctr.c
- src/crypto/rand_urandom_chacha20/rand_urandom_chacha20.c
- src/crypto/sha3/sha3.c
- src/kex/test_kex.c
- src/kex_code_mcbits/kex_code_mcbits.c
- src/kex_lwe_frodo/kex_lwe_frodo_macrify.c
- src/kex_mlwe_kyber/kex_mlwe_kyber.c
- src/kex_mlwe_kyber/verify.c
- src/kex_ntru/kex_ntru.c
- src/kex_rlwe_bcns15/kex_rlwe_bcns15.c
- src/kex_rlwe_bcns15/rlwe.c
- src/kex_rlwe_msrln16/kex_rlwe_msrln16.c
- src/kex_rlwe_newhope/kex_rlwe_newhope.c
- src/kex_sidh_cln16/kex_sidh_cln16.c
- src/sig/test_sig.c
- src/sig_picnic/Makefile.am
- src/sig_picnic/sig_picnic.c
Updated Visual Studio solution to 2017 version, fixed build warnings (issue #159), added signature and Picnic support.
> Updated Windows build (added sig, fixed warnings, 2017 update)

- appveyor.yml
> Vsoftco issue160

- VisualStudio/oqs/oqs.vcxproj
- VisualStudio/oqs/oqs.vcxproj.filters
- src/kex/kex.c
- src/kex_sidh_msr/P503/P503_api.h
- src/kex_sidh_msr/P751/P751_api.h
- src/kex_sidh_msr/kex_sidh_msr.c
- src/kex_sidh_msr/sike.c
- src/kex_sidh_msr/windows_undef.h
(Re)Added SIDHv3/SIKE to Visual Studio.
> (Re)Added SIDHv3/SIKE to Visual Studio.

- .gitignore
- .travis/global-namespace-check.sh
- Makefile.am
- README.md
- src/kex/minimal_kex_oqs.c
- src/sig/minimal_sig_oqs.c
> Issue 187 and 207

- src/common/common.c
- src/common/common.h
> added const to uint8_t *str pointer in OQS_print

- src/kex_sidh_msr/kex_sidh_msr.c
- src/sig/sig.c
- src/sig/sig.h
- src/sig_picnic/sig_picnic.c
- src/sig_picnic/sig_picnic.h
Replaced malloc with calloc to address a confused valgrind. Fixes issue #229.
> Fix issue 229

- .travis/license-check.sh
- src/kem/crystals-kyber/upstream/LICENSE.txt
> Add Kyber license and license-check script to Travis

- .travis/free-check.sh
- src/common/common.c
- src/common/common.h
- src/kem/example_kem.c
- src/kem/kat_kem.c
- src/kem/kem.c
- src/kem/speed_kem.c
- src/kem/test_kem.c
> Check for usage of free versus `OQS_MEM_secure_free`

- .gitignore
- src/kex/minimal_kex_oqs.c
- src/kex_code_mcbits/kex_code_mcbits.c
- src/kex_lwe_frodo/kex_lwe_frodo.c
- src/kex_ntru/kex_ntru.c
- src/kex_rlwe_bcns15/kex_rlwe_bcns15.c
- src/kex_rlwe_msrln16/kex_rlwe_msrln16.c
- src/kex_rlwe_newhope/kex_rlwe_newhope.c
- src/kex_sidh_iqc_ref/kex_sidh_iqc_ref.c
- src/kex_sidh_msr/kex_sidh_msr.c
- src/sig/minimal_sig_oqs.c
replaced free by OQS_MEM_secure_free where necessary
> Fix alice_priv_free in implementations

- .travis.yml
- .travis/all-tests.sh
- docs/.Doxyfile
- src/common/common.h
- src/common/rand.h
- src/crypto/aes/aes.h
- src/crypto/rand_urandom_aesctr/rand_urandom_aesctr.h
- src/crypto/rand_urandom_chacha20/rand_urandom_chacha20.h
- src/kex/kex.h
- src/kex_code_mcbits/kex_code_mcbits.h
- src/kex_ntru/kex_ntru.c
- src/kex_ntru/kex_ntru.h
- src/kex_ntru/ntru_crypto_platform.h
- src/kex_rlwe_newhope/kex_rlwe_newhope.h
- src/kex_sidh_msr/kex_sidh_msr.h
- src/sig/sig.h
> Make doxygen mandatory and fix undocumented functions / add deprecation notices

- Makefile
- README.md
- scripts/build-keccak-code-package.sh
> Update URL and ZIP file name for Keccak code package

- VisualStudio/liboqs.sln
- VisualStudio/minimal_kex_oqs/minimal_kex_oqs.vcxproj
- VisualStudio/minimal_kex_oqs/minimal_kex_oqs.vcxproj.filters
- VisualStudio/minimal_sig_oqs/minimal_sig_oqs.vcxproj
- VisualStudio/minimal_sig_oqs/minimal_sig_oqs.vcxproj.filters
- VisualStudio/oqs/oqs.vcxproj
- VisualStudio/oqs/oqs.vcxproj.filters
- VisualStudio/test_kex/test_kex.vcxproj
- VisualStudio/test_kex/test_kex.vcxproj.filters
- VisualStudio/test_sig/test_sig.vcxproj
- VisualStudio/test_sig/test_sig.vcxproj.filters
- appveyor.yml
- src/common/common.h
- src/common/rand.c
- tests/minimal_kex_oqs.c
Simply fixed VS solution without adding new content, and removed test_rand project from the solution. Next, I'll add new KEM api and algorithms.
> Fixed Visual Studio build after master's API refactoring.

- VisualStudio/liboqs.sln
- VisualStudio/oqs/oqs.vcxproj
- VisualStudio/oqs/oqs.vcxproj.filters
- VisualStudio/test_kem/test_kem.vcxproj
- VisualStudio/test_kem/test_kem.vcxproj.filters
- VisualStudio/winconfig.h
- appveyor.yml
- src/common/rand.c
- src/kem/kem.c
Added the KEM API and frodokem to the Visual Studio build. Also fixed the call the Window's system randomness, and released the crypto context (fixing issue #349).
> Adds KEM API and frodokem to Visual Studio

- docs/algorithms/kem_titanium.md
Ron Steinfeld wanted the following updates to the data sheet:
"It would be more accurate to say that the cryptographic assumption underlying Titanium is hardness of "Middle-Product Learning with Errors (MP-LWE)". The latter problem is at least as hard as PLWE over many rings, as explained in our security analysis documentation for Titanium."
> Titanium: tweak data sheet with author's updates.

- .gitignore
- README.md
> Fix some typos

- src/sig/example_sig.c
- src/sig/sig.c
Fixes some little issues with sig API.
> Sig API fixes

- src/common/common.h
- src/kem/bike/upstream/additional_implementation/defs.h
- src/kem/bike/upstream/reference_implementation/defs.h
Mapped BIKE-specific error codes to OQS_error. Fixes issue #421.
> Removed BIKE-specific OQS status code (issue 421).

- .travis/algorithm-datasheets-check.sh
- docs/.Doxyfile
- src/common/common.c
- src/common/common.h
- src/common/rand.c
- src/common/rand.h
- src/kem/kat_kem.c
- src/kem/kem.c
- src/kem/kem.h
- src/kem/test_kem.c
- src/sig/sig.c
- src/sig/sig.h
Still need to add alg\_version fields for all KEM and SIG algorithms as per #413
> Sync nist-branch with master and sort algorithms alphabetically

- tests/example_sig.c
> Fix typo in sig name in comment block

- .gitignore
- Makefile
- README.md
- src/common/common.h
- src/kem/bike/upstream/additional_implementation/defs.h
- src/kem/example_kem.c
- src/oqs.h
- src/sig/example_sig.c
> Rename OQS' config.h to oqsconfig.h

- .gitignore
- Makefile.am
- README.md
- config/features.m4
- src/common/common.h
- src/kem/bike/Makefile.am
- src/kem/bike/kem_bike.c
- src/kem/bike/kem_bike.h
- src/kem/bike/ref/types.h
- src/kem/bike/x86_64/defs.h
- src/kem/bike/x86_64/types.h
- src/oqs.h
- tests/example_kem.c
- tests/example_sig.c
> Rename OQS' config.h to oqsconfig.h and separate autoconf variables

- README.md
> Add ARM instructions to README.md

- CONTRIBUTING.md
Alert users the integration process can be mostly automated, giving them the option to try it or not :-)
> Link to liboqs-utils project in CONTRIBUTING.md

- README.md
Replicates #455 for nist branch.
> Specified the intended use of liboqs default algorithms

- VisualStudio/oqs/oqs.vcxproj
- VisualStudio/oqs/oqs.vcxproj.filters
- scripts/copy_from_pqclean/VisualStudio/oqs/oqs.vcxproj.filters/clcompile.fragment
- scripts/copy_from_pqclean/VisualStudio/oqs/oqs.vcxproj.filters/clinclude.fragment
- scripts/copy_from_pqclean/VisualStudio/oqs/oqs.vcxproj.filters/filter.fragment
- scripts/copy_from_pqclean/VisualStudio/oqs/oqs.vcxproj/clinclude.fragment
- scripts/copy_from_pqclean/copy_from_pqclean.yml
> Fix Visual Studio filter file for KEMs generated by template

- VisualStudio/oqs/oqs.vcxproj.filters
> Add Dilithium to VS filters

- .travis.yml
- README.md
- config/detect_host_and_cpu.m4
- src/kem/sike/Makefile.am
- src/kem/sike/P434/AMD64/fp_x64.c
- src/kem/sike/P434/P434.c
- src/kem/sike/P434/generic/fp_generic.c
- src/kem/sike/P503/AMD64/fp_x64.c
- src/kem/sike/P503/ARM64/fp_arm64.c
- src/kem/sike/P503/P503.c
- src/kem/sike/P503/generic/fp_generic.c
- src/kem/sike/P610/AMD64/fp_x64.c
- src/kem/sike/P610/P610.c
- src/kem/sike/P610/generic/fp_generic.c
- src/kem/sike/P751/AMD64/fp_x64.c
- src/kem/sike/P751/ARM64/fp_arm64.c
- src/kem/sike/P751/P751.c
- src/kem/sike/P751/generic/fp_generic.c
- src/kem/sike/config.h
- src/kem/sike/kem_sike.h
Resolves config FIXMEOQSs, and addresses issue #512.
> Set SIKE's Makefile.am options from configure

- VisualStudio/winconfig.h
- configure.ac
- scripts/git_commit.sh
- tests/Makefile.am
- tests/kat_kem.c
- tests/kat_sig.c
- tests/speed_kem.c
- tests/speed_sig.c
- tests/system_info.c
- tests/test_aes.c
- tests/test_hash.c
- tests/test_kem.c
- tests/test_sha3.c
- tests/test_sig.c
> Add macros containing compilation information and print in test programs

- .gitignore
- VisualStudio/oqs/dll.def
- scripts/copy_from_pqclean/VisualStudio/oqs/dll.def
- scripts/copy_from_pqclean/src/kem/kem.c/enabled_case.fragment
- scripts/copy_from_pqclean/src/sig/sig.c/enabled_case.fragment
- src/common/common.h
- src/kem/kem.c
- src/kem/kem.h
- src/sig/sig.c
- src/sig/sig.h
- tests/test_kem.c
- tests/test_sig.c
> Add functions to test if algorithms are enabled

- appveyor.yml
- src/kem/sike/config.h
Reverts open-quantum-safe/liboqs#540
> Revert "Fix build failure on Visual Studio x86"

- docs/algorithms/kem_sike.md
- src/kem/sike/P434/P434.c
- src/kem/sike/P434/P434_api.h
- src/kem/sike/P434/P434_compressed.c
- src/kem/sike/P434/P434_compressed_api.h
- src/kem/sike/P503/P503.c
- src/kem/sike/P503/P503_api.h
- src/kem/sike/P503/P503_compressed.c
- src/kem/sike/P503/P503_compressed_api.h
- src/kem/sike/P503/P503_internal.h
- src/kem/sike/P610/P610.c
- src/kem/sike/P610/P610_api.h
- src/kem/sike/P610/P610_compressed.c
- src/kem/sike/P610/P610_compressed_api.h
- src/kem/sike/P751/P751.c
- src/kem/sike/P751/P751_api.h
- src/kem/sike/P751/P751_compressed.c
- src/kem/sike/P751/P751_compressed_api.h
- src/kem/sike/compression/sidh_compressed.c
- src/kem/sike/ec_isogeny.c
- src/kem/sike/fpx.c
- src/kem/sike/kem_sike.c
- src/kem/sike/sidh.c
Integrated Sike's latest update, including doc typo and a security fix.
> Integrated SIKE's nov-dec 2019 updates

- config/detect_host_and_cpu.m4
- tests/ds_benchmark.h
- tests/speed_kem.c
- tests/speed_sig.c
- tests/test_aes.c
> Don't use cycle count register on Raspberry Pi

- tests/example_sig.c
> Fix memory leak on example_sig

- .CMake/toolchain-rasppi.cmake
- README.md
I've successfully cross compiled this. Currently running it on my Raspberry Pi and will convert it to a non-draft pull request once it passes.
> Add toolchain for Raspberry Pi cross compilation

- .circleci/config.yml
This will surface another set of errors.
> Add UBSAN builds to CI

- src/common/rand.c
- src/kem/kem.c
- src/sig/sig.c
- tests/CMakeLists.txt
- tests/ds_benchmark.h
- tests/test_sha3.c
Builds successfully on Arch Linux and passes tests in Wine
> Mingw-w64 support

- CMakeLists.txt
- scripts/build-android.sh
Add build script and modify CMakeLists.txt to fix pieces which break Android build.
> Enable cross-compilation for Android

- .CMake/compiler_flags.cmake
- scripts/copy_from_pqclean/src/kem/family/kem_family.h
- scripts/copy_from_pqclean/src/sig/family/sig_family.h
- src/CMakeLists.txt
- src/common/CMakeLists.txt
- src/common/aes/aes_c.c
- src/common/aes/aes_ossl.c
- src/common/common.h
- src/common/rand/rand.c
- src/common/rand/rand_nist.c
- src/common/sha2/sha2_c.c
- src/kem/kyber/kem_kyber.h
- src/kem/ledacrypt/kem_ledacrypt.h
- src/kem/newhope/kem_newhope.h
- src/kem/ntru/kem_ntru.h
- src/kem/saber/kem_saber.h
- src/kem/threebears/kem_threebears.h
- src/sig/dilithium/sig_dilithium.h
- src/sig/mqdss/sig_mqdss.h
- src/sig/sphincs/sig_sphincs.h
- tests/CMakeLists.txt
- tests/ds_benchmark.h
- tests/example_kem.c
- tests/kat_kem.c
- tests/kat_sig.c
- tests/speed_kem.c
- tests/speed_sig.c
- tests/test_aes.c
- tests/test_hash.c
- tests/test_kem.c
Will address `-Wmissing-prototypes` in a future PR.
> Enabled some more Clang warning flags and fixed bugs

- CONTRIBUTORS
Thanks @xvzcf for the reminder
> As per suggestion

- .circleci/config.yml
> Reenable qTesla CI on ARM

- src/kem/sike/CMakeLists.txt
Fixes https://github.com/open-quantum-safe/liboqs/issues/718
> SIKE build fix on ARM64

- appveyor_build.bat
- scripts/build-android.sh
- scripts/copy_from_pqclean/src/kem/family/CMakeLists.txt
- scripts/copy_from_pqclean/src/kem/family/kem_scheme.c
- scripts/copy_from_pqclean/src/sig/family/CMakeLists.txt
- scripts/copy_from_pqclean/src/sig/family/sig_scheme.c
- src/common/rand/rand.h
- src/common/rand/rand_nist.c
- src/kem/frodokem/CMakeLists.txt
- src/kem/frodokem/external/frodo1344aes.c
- src/kem/frodokem/external/frodo1344shake.c
- src/kem/frodokem/external/frodo640aes.c
- src/kem/frodokem/external/frodo640shake.c
- src/kem/frodokem/external/frodo976aes.c
- src/kem/frodokem/external/frodo976shake.c
- src/kem/frodokem/external/frodo_macrify_optimized.c
- tests/kat_kem.c
- tests/kat_sig.c
I'll run `copy_from_pqclean.py` and push another commit once the present changes have been reviewed.
> Refactoring

- docs/algorithms/kem_frodokem.md
- docs/algorithms/sig_qtesla.md
Updated license and implementation source.
> update qtesla alg doc

- LICENSE.txt
- src/common/CMakeLists.txt
@xvzcf Could you please check whether you can see how (C)CI runs on this change? As discussed, I'm now trying to do a PR from 'within' OQS and not my own fork -- and all kind of weird things happen (not seeing CCI results being one thing). Locally things look OK. Thanks in advance.
> fixes issue 757

- src/common/sha3/sha3.h
Removed an (unnecessary) AES prerequisites test (and checking whether CCI now gets displayed if I do a PR....)
> additional fix for issue 757 (cudos to @xvzcf)

- src/kem/frodokem/external/frodo1344aes.c
- src/kem/frodokem/external/frodo1344shake.c
- src/kem/frodokem/external/frodo640aes.c
- src/kem/frodokem/external/frodo640shake.c
- src/kem/frodokem/external/frodo976aes.c
- src/kem/frodokem/external/frodo976shake.c
- src/kem/frodokem/external/frodo_internal.h
- src/kem/frodokem/external/kem.c
- src/kem/frodokem/external/util.c
As identified in: Qian Guo, Thomas Johansson, Alexander Nilsson. A key-recovery timing attack on post-quantum primitives using the Fujisaki-Okamoto transformation and its application on FrodoKEM. In CRYPTO 2020.
> Fix timing leak during decapsulation

- docs/algorithms/kem/sike.md
- src/kem/sike/external/P434/ARM64/fp_arm64_asm.S
- src/kem/sike/external/P434/generic/fp_generic.c
- src/kem/sike/external/P503/generic/fp_generic.c
- src/kem/sike/external/P610/generic/fp_generic.c
- src/kem/sike/external/P751/generic/fp_generic.c
- src/kem/sike/external/fpx.c
- src/kem/sike/kem_sike.c
- tests/test_kem.c
- tests/test_sig.c
Integrated SIKE upstream commits from 521aab to 50f352, including a fix for a crash when fed garbage data. Added extra test from PR #787. Fixes issue #788.
> Integrated latest SIKE bug fixes

- src/kem/frodokem/external/frodo_macrify_optimized.c
Partially addresses #807 
* [No] Does this PR change the the list of algorithms available -- either adding or removing?  (If so, PRs in OQS-OpenSSL, OQS-BoringSSL, and OQS-OpenSSH will also be required by the time this is merged.)
> Fix undefined behaviour in FrodoKEM

- .circleci/config.yml
- src/common/common.c
- src/common/common.h
- tests/CMakeLists.txt
- tests/system_info.c
> addressing #802

- .circleci/config.yml
To be paired with: https://github.com/open-quantum-safe/boringssl/pull/31
> Added flag to payload sent by CircleCI to trigger downstream CI.

- .circleci/config.yml
Apologies for this silly mistake.
> Fixed format of JSON payloads in CircleCI job.

- docs/algorithms/kem/sike.md
Updated SIKE p751 security level in algorithm's documentation.
> Fixed SIKE p751 in alg doc.

- .circleci/config.yml
> Removed CentOS 7 from CI.

- docs/.Doxyfile
- docs/algorithms/sig/rainbow.md
Add note about Rainbow cryptanalysis.
> Documentation updates

- .circleci/config.yml
- src/CMakeLists.txt
@christianpaquin could you verify OQS-OpenSSL still builds on Windows with this PR?
> Exporting liboqs target in CMake and some CI refactoring.

- .circleci/config.yml
- src/CMakeLists.txt
> Triggering more downstream CircleCI jobs.

- docs/algorithms/kem/frodokem.md
- src/kem/frodokem/external/util.c
- src/kem/frodokem/kem_frodokem1344aes.c
- src/kem/frodokem/kem_frodokem1344shake.c
- src/kem/frodokem/kem_frodokem640aes.c
- src/kem/frodokem/kem_frodokem640shake.c
- src/kem/frodokem/kem_frodokem976aes.c
- src/kem/frodokem/kem_frodokem976shake.c
Integrates frodokem commit 669522. Fixes issue #868.
> Integrates frodokem Dec 2020 update

- tests/test_portability.py
> Changing python platform check

- .github/CODEOWNERS
Activates Github's [code owners feature](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) to help direct code reviews.
> First attempt at a CODEOWNERS file [skip ci]

- scripts/copy_from_upstream/copy_from_upstream.py
- scripts/copy_from_upstream/requirements.txt
Opening this PR for discussion around whether we want a patch mechanism for copy from upstream.
This PR contains a functioning patch mechanism. The documentation is here:
https://gist.github.com/jschanck/c67d37551da2a5f6e06c640816d2c99f
> Patch mechanism for copy from upstream

- .circleci/config.yml
- docs/algorithms/kem/classic_mceliece.md
- docs/algorithms/kem/hqc.md
- docs/algorithms/kem/ntru.md
- docs/algorithms/kem/ntruprime.md
- docs/algorithms/kem/saber.md
- docs/algorithms/sig/falcon.md
- docs/algorithms/sig/rainbow.md
- docs/algorithms/sig/sphincs.md
- scripts/copy_from_upstream/copy_from_upstream.yml
- src/kem/hqc/kem_hqc_128.c
- src/kem/hqc/kem_hqc_192.c
- src/kem/hqc/kem_hqc_256.c
- src/kem/hqc/pqclean_hqc-rmrs-128_avx2/gf2x.c
- src/kem/hqc/pqclean_hqc-rmrs-128_avx2/reed_solomon.c
- src/kem/hqc/pqclean_hqc-rmrs-192_avx2/gf2x.c
- src/kem/hqc/pqclean_hqc-rmrs-192_avx2/reed_solomon.c
- src/kem/hqc/pqclean_hqc-rmrs-256_avx2/gf2x.c
- src/kem/hqc/pqclean_hqc-rmrs-256_avx2/reed_solomon.c
Fixes #953.
* [No] Does this PR change the the list of algorithms available -- either adding, removing, or renaming?  (If so, PRs in OQS-OpenSSL, OQS-BoringSSL, and OQS-OpenSSH will also be required by the time this is merged.)
> Sync with PQClean

- RELEASE.md
> Update RELEASE notes with new build flags [skip ci]

- docs/algorithms/kem/sike.md
- src/kem/sike/external/compression/dlog.c
- src/kem/sike/kem_sike.c
Integrates SIKE March 2021 bug fix. Fixes #979.
> SIKE March 2021 bug fix

- docs/algorithms/kem/classic_mceliece.md
- docs/algorithms/kem/hqc.md
- docs/algorithms/kem/ntru.md
- docs/algorithms/kem/ntruprime.md
- docs/algorithms/kem/saber.md
- docs/algorithms/sig/falcon.md
- docs/algorithms/sig/rainbow.md
- docs/algorithms/sig/sphincs.md
- scripts/copy_from_upstream/copy_from_upstream.yml
- src/kem/hqc/kem_hqc_128.c
- src/kem/hqc/kem_hqc_192.c
- src/kem/hqc/kem_hqc_256.c
- src/kem/hqc/pqclean_hqc-rmrs-192_avx2/reed_solomon.c
> Pull latest HQC-192 from PQClean

- src/kem/kem.h
> Consistent type in KEM decaps API

- .circleci/config.yml
> ARM64 via CCI machine

- .circleci/config.yml
> Fixed downstream triggering bug in CircleCI config and also refactored the config.yml

- scripts/copy_from_upstream/copy_from_upstream.py
- scripts/copy_from_upstream/src/kem/kem.h/algs_length.fragment
- scripts/copy_from_upstream/src/sig/sig.h/algs_length.fragment
> use doc YMLs to count non-copy-from-upstream algs [skip ci]

- .circleci/config.yml
- appveyor.yml
- docs/algorithms/kem/sike.md
- docs/algorithms/kem/sike.yml
- tests/CMakeLists.txt
- tests/dump_alg_info.c
- tests/test_alg_info.py
Based on discussion in https://github.com/open-quantum-safe/openssl/pull/316#issuecomment-893521915.
> Add test suite comparing parameters in C with parameters in YML

- tests/constant_time/kem/issues.json
- tests/constant_time/kem/passes.json
- tests/constant_time/kem/passes/sntrup
Updating the Valgrind suppression files to deal with the following recent changes:
- NTRU Prime code changed slightly so line offset has to change.
- BIKE variants changed names.
> Update Valgrind suppression files for recent implementation changes

- scripts/noregress.py
- scripts/noregress.sh
Added MIT spdx headers to noregress.py and noregress.sh as found in #1153.
> Added spdx headers to noregress.[py|sh]

- tests/constant_time/sig/passes/picnic
- tests/constant_time/sig/passes/picnic3
> Updated constant_time suppression files after picnic update

- .github/workflows/weekly.yml
Another attempt at getting weekly testing right as github action 
> Weekly run update

- src/CMakeLists.txt
- src/Config.cmake.in
- tests/CMakeLists.txt
> create and install cmake import files

- .circleci/config.yml
- docs/algorithms/kem/kyber.md
- docs/algorithms/kem/kyber.yml
- scripts/copy_from_upstream/copy_from_upstream.yml
- scripts/copy_from_upstream/patches/pqcrystals-kyber-avx2-shake-aes.patch
- src/kem/kyber/pqcrystals-kyber_kyber1024-90s_avx2/indcpa.c
- src/kem/kyber/pqcrystals-kyber_kyber1024_avx2/indcpa.c
- src/kem/kyber/pqcrystals-kyber_kyber512-90s_avx2/indcpa.c
- src/kem/kyber/pqcrystals-kyber_kyber512_avx2/indcpa.c
- src/kem/kyber/pqcrystals-kyber_kyber768-90s_avx2/indcpa.c
- src/kem/kyber/pqcrystals-kyber_kyber768_avx2/indcpa.c
- Syncs Kyber with upstream https://github.com/pq-crystals/kyber/commit/8e00ec73035147d18b27d06048dff322f8de1f29
- copy_from_upstream
- Enables scan-build for Kyber
- Updates Kyber docs
Fixes #1248
> Sync Kyber with upstream, enable Scan-Build with Kyber

- tests/CMakeLists.txt
> Build dump_alg_info in tests

- .circleci/config.yml
- CMakeLists.txt
- docs/.Doxyfile
- scripts/run_doxygen.sh
> Build Doxygen docs in whatever the CMake build directory is

- src/kem/frodokem/external/kem.c
> Use OQS_STATUS types in FrodoKEM

- CONFIGURE.md
Documentation clarification for OQS_USE_OPENSSL
> clarify OpenSSL config [skip ci]

- .github/pull_request_template.md
> rm duped "the" in pull_request_template.md

- docs/algorithms/sig/sphincs.md
- docs/algorithms/sig/sphincs.yml
> Update SPHINCS+ specification version [skip ci]

- src/common/common.c
Dependent on #1653.
`set_available_cpu_extensions()` is synchronized with a thread-unsafe array element. This is similar to #1549, except in this case instead of causing any crashes, the thread-unsafe behaviour simply leads some early callers to believe that the relevant CPU extensions are not available, and hence use reference implementations instead before the extensions are eventually calculated. This can and has set off TSAN.
It is also possible in rare instances for the thread calling `set_available_cpu_extensions()` to set `cpu_ext_data[OQS_CPU_EXT_INIT] = 1` and then crash before setting any of the other `cpu_ext_data` fields, preventing future callers from ever calling `set_available_cpu_extensions()` again, thus causing the program to use only reference implementations for its …
> Call set_available_cpu_extensions using pthread_once

- docs/algorithms/sig/sphincs.md
I used "[skip ci]" a little too liberally on #1683 and missed the fact that Markdown documentation needed to be updated to reflect YAML changes. This PR does that.
> Update Sphincs+ Markdown documentation from YAML

- .github/workflows/release-test.yml
Adds the ability to manually trigger the release-test workflow
* No 
* No
> Add workflow dispatch to action

- CONFIGURE.md
- src/common/common.c
- src/sig_stfl/lms/sig_stfl_lms.c
- src/sig_stfl/lms/sig_stfl_lms.h
- src/sig_stfl/xmss/external/wots.c
- src/sig_stfl/xmss/external/xmss_core_fast.c
Signed-off-by: Duc Tri Nguyen <dnguye69@gmu.edu>
> Zeroing internal state memory on heap

- docs/algorithms/sig_stfl/lms.md
- docs/algorithms/sig_stfl/lms.yml
- docs/algorithms/sig_stfl/xmss.md
- docs/algorithms/sig_stfl/xmss.yml
- src/sig_stfl/lms/sig_stfl_lms.c
- src/sig_stfl/lms/sig_stfl_lms_functions.c
Cleans up some old unresolved comments of mine that got buried in the GitHub interface.
> Clean up unresolved comments on stateful-sigs PR

- tests/test_kem_vectors.sh
- tests/vectors_kem.c
Thank you for catching the issue @abhinav-thales! Could you please confirm if this fixes the issue?
Fixes #1853
> ML-KEM NIST tests, fix order of d and z

- README.md
Adds badges for main branch tests and weekly tests to README
Fixes #1984
> chore: Add CI badges to README.md

- CONTRIBUTING.md
Clarifies expectations for contributions to ease maintainability
* [no] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in fully supported downstream projects dependent on these, i.e., [oqs-provider](https://github.com/open-quantum-safe/oqs-provider) will also need to be ready for review and merge by the time this is merged.)
> improving CONTRIBUTING.md for maintainability [skip ci]

- README.md
- SECURITY.md
Adds the support caveat suggested by Michael in #2065.
Closes #2065.
> Add support caveat

- flake.lock
Updating the Nix flake inputs here as a chore. I don't think there's any urgent security need for it, but I figured it would be good.
> Update Nix flake inputs

- .github/workflows/commit-to-main.yml
- .github/workflows/supplychain.yml
Try to fix https://github.com/open-quantum-safe/liboqs/actions/runs/17043292457
> Fix permissions for poutine_analysis job
